// This file is auto-generated by @hey-api/openapi-ts
import { createClient } from '@hey-api/client-fetch';

export * from './types.gen';
export * from './sdk.gen';
export * from './client.gen';
export { createClient };

export interface ApiClientConfig {
  baseUrl?: string;
  tenantId?: string;
  headers?: Record<string, string>;
}

export function createApiClient(config: ApiClientConfig = {}) {
  return createClient({
    baseUrl: config.baseUrl,
    headers: {
      ...(config.tenantId ? { 'X-Tenant-ID': config.tenantId } : {}),
      ...config.headers,
    },
  });
}