// This file is auto-generated by @hey-api/openapi-ts

import { type Options as ClientOptions, type TDataShape, type Client, formDataBodySerializer } from '@hey-api/client-fetch';
import type { GetHealthData, GetHealthResponse, GetHealthError, ListAccountingAccountsData, ListAccountingAccountsResponse, ListAccountingAccountsError, CreateAccountingAccountData, CreateAccountingAccountResponse, CreateAccountingAccountError, GetAccountingAccountData, GetAccountingAccountResponse, GetAccountingAccountError, UpdateAccountingAccountData, UpdateAccountingAccountResponse, UpdateAccountingAccountError, ListJournalEntriesData, ListJournalEntriesResponse, ListJournalEntriesError, CreateJournalEntryData, CreateJournalEntryResponse, CreateJournalEntryError, GetJournalEntryData, GetJournalEntryResponse, GetJournalEntryError, PostJournalEntryData, PostJournalEntryResponse, PostJournalEntryError, ListDteInvoicesData, ListDteInvoicesResponse, ListDteInvoicesError, CreateDteInvoiceData, CreateDteInvoiceResponse, CreateDteInvoiceError, GetDteInvoiceData, GetDteInvoiceResponse, GetDteInvoiceError, IssueDteInvoiceData, IssueDteInvoiceResponse, IssueDteInvoiceError, ListExpensesData, ListExpensesResponse, ListExpensesError, CreateExpenseData, CreateExpenseResponse, CreateExpenseError, GetExpenseData, GetExpenseResponse, GetExpenseError, UpdateExpenseData, UpdateExpenseResponse, UpdateExpenseError, ListDocumentsData, ListDocumentsResponse, ListDocumentsError, CreateDocumentData, CreateDocumentResponse, CreateDocumentError, GetDocumentData, GetDocumentResponse, GetDocumentError, GetDocumentContentData, GetDocumentContentResponse, GetDocumentContentError } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
};

/**
 * Health check
 */
export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetHealthResponse, GetHealthError, ThrowOnError>({
        url: '/health',
        ...options
    });
};

/**
 * Listar cuentas contables
 */
export const listAccountingAccounts = <ThrowOnError extends boolean = false>(options: Options<ListAccountingAccountsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<ListAccountingAccountsResponse, ListAccountingAccountsError, ThrowOnError>({
        url: '/accounting/accounts',
        ...options
    });
};

/**
 * Crear cuenta contable
 */
export const createAccountingAccount = <ThrowOnError extends boolean = false>(options: Options<CreateAccountingAccountData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateAccountingAccountResponse, CreateAccountingAccountError, ThrowOnError>({
        url: '/accounting/accounts',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Obtener cuenta contable
 */
export const getAccountingAccount = <ThrowOnError extends boolean = false>(options: Options<GetAccountingAccountData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetAccountingAccountResponse, GetAccountingAccountError, ThrowOnError>({
        url: '/accounting/accounts/{accountId}',
        ...options
    });
};

/**
 * Actualizar cuenta contable
 */
export const updateAccountingAccount = <ThrowOnError extends boolean = false>(options: Options<UpdateAccountingAccountData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).patch<UpdateAccountingAccountResponse, UpdateAccountingAccountError, ThrowOnError>({
        url: '/accounting/accounts/{accountId}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Listar asientos contables
 */
export const listJournalEntries = <ThrowOnError extends boolean = false>(options: Options<ListJournalEntriesData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<ListJournalEntriesResponse, ListJournalEntriesError, ThrowOnError>({
        url: '/accounting/journal-entries',
        ...options
    });
};

/**
 * Crear asiento contable
 * Crea un asiento en estado draft.
 *
 * El backend debe validar que la suma de débitos sea igual a la suma de créditos.
 *
 */
export const createJournalEntry = <ThrowOnError extends boolean = false>(options: Options<CreateJournalEntryData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateJournalEntryResponse, CreateJournalEntryError, ThrowOnError>({
        url: '/accounting/journal-entries',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Obtener asiento contable
 */
export const getJournalEntry = <ThrowOnError extends boolean = false>(options: Options<GetJournalEntryData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetJournalEntryResponse, GetJournalEntryError, ThrowOnError>({
        url: '/accounting/journal-entries/{entryId}',
        ...options
    });
};

/**
 * Postear asiento contable
 * Cambia un asiento de draft a posted.
 *
 * Solo debe permitirse si el asiento está balanceado.
 *
 */
export const postJournalEntry = <ThrowOnError extends boolean = false>(options: Options<PostJournalEntryData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostJournalEntryResponse, PostJournalEntryError, ThrowOnError>({
        url: '/accounting/journal-entries/{entryId}/post',
        ...options
    });
};

/**
 * Listar DTE
 */
export const listDteInvoices = <ThrowOnError extends boolean = false>(options: Options<ListDteInvoicesData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<ListDteInvoicesResponse, ListDteInvoicesError, ThrowOnError>({
        url: '/invoicing/dte',
        ...options
    });
};

/**
 * Registrar DTE
 * Registra un DTE interno en estado draft.
 *
 * La emisión real ante SII se gestiona mediante el endpoint de issue.
 *
 */
export const createDteInvoice = <ThrowOnError extends boolean = false>(options: Options<CreateDteInvoiceData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateDteInvoiceResponse, CreateDteInvoiceError, ThrowOnError>({
        url: '/invoicing/dte',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Obtener DTE
 */
export const getDteInvoice = <ThrowOnError extends boolean = false>(options: Options<GetDteInvoiceData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetDteInvoiceResponse, GetDteInvoiceError, ThrowOnError>({
        url: '/invoicing/dte/{dteId}',
        ...options
    });
};

/**
 * Emitir DTE
 * Marca el DTE como emitido.
 *
 * En fases posteriores, este endpoint integrará SII.
 *
 */
export const issueDteInvoice = <ThrowOnError extends boolean = false>(options: Options<IssueDteInvoiceData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<IssueDteInvoiceResponse, IssueDteInvoiceError, ThrowOnError>({
        url: '/invoicing/dte/{dteId}/issue',
        ...options
    });
};

/**
 * Listar gastos
 */
export const listExpenses = <ThrowOnError extends boolean = false>(options: Options<ListExpensesData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<ListExpensesResponse, ListExpensesError, ThrowOnError>({
        url: '/expenses',
        ...options
    });
};

/**
 * Crear gasto
 */
export const createExpense = <ThrowOnError extends boolean = false>(options: Options<CreateExpenseData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateExpenseResponse, CreateExpenseError, ThrowOnError>({
        url: '/expenses',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Obtener gasto
 */
export const getExpense = <ThrowOnError extends boolean = false>(options: Options<GetExpenseData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetExpenseResponse, GetExpenseError, ThrowOnError>({
        url: '/expenses/{expenseId}',
        ...options
    });
};

/**
 * Actualizar gasto
 */
export const updateExpense = <ThrowOnError extends boolean = false>(options: Options<UpdateExpenseData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).patch<UpdateExpenseResponse, UpdateExpenseError, ThrowOnError>({
        url: '/expenses/{expenseId}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Listar documentos
 */
export const listDocuments = <ThrowOnError extends boolean = false>(options: Options<ListDocumentsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<ListDocumentsResponse, ListDocumentsError, ThrowOnError>({
        url: '/documents',
        ...options
    });
};

/**
 * Subir documento
 * Sube un documento binario y registra sus metadatos.
 *
 * Usar multipart/form-data.
 *
 */
export const createDocument = <ThrowOnError extends boolean = false>(options: Options<CreateDocumentData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateDocumentResponse, CreateDocumentError, ThrowOnError>({
        ...formDataBodySerializer,
        url: '/documents',
        ...options,
        headers: {
            'Content-Type': null,
            ...options?.headers
        }
    });
};

/**
 * Obtener metadatos de documento
 */
export const getDocument = <ThrowOnError extends boolean = false>(options: Options<GetDocumentData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetDocumentResponse, GetDocumentError, ThrowOnError>({
        url: '/documents/{documentId}',
        ...options
    });
};

/**
 * Descargar contenido de documento
 */
export const getDocumentContent = <ThrowOnError extends boolean = false>(options: Options<GetDocumentContentData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetDocumentContentResponse, GetDocumentContentError, ThrowOnError>({
        url: '/documents/{documentId}/content',
        ...options
    });
};