// This file is auto-generated by @hey-api/openapi-ts

export type Uuid = string;

export type _Date = string;

export type DateTime = string;

/**
 * Número decimal enviado como string para evitar errores de punto flotante. Hasta 2 decimales.
 */
export type DecimalString = string;

/**
 * Número decimal no negativo enviado como string. Hasta 2 decimales.
 */
export type NonNegativeDecimalString = string;

/**
 * Rol Único Tributario (RUT) chileno con o sin puntos y con guion y dígito verificador (0-9 o K).
 */
export type ChileanRut = string;

export type HealthResponse = {
    status: 'ok';
    service: string;
    version: string;
};

export type PageMeta = {
    page: number;
    page_size: number;
    total: number;
    total_pages: number;
};

export type ErrorDetail = {
    field: string;
    message: string;
    code?: string;
};

export type ProblemDetail = {
    type?: string;
    title: string;
    status: number;
    detail?: string;
    instance?: string;
    errors?: Array<ErrorDetail>;
};

export type AccountType = 'asset' | 'liability' | 'equity' | 'income' | 'expense';

export type JournalStatus = 'draft' | 'posted' | 'voided';

/**
 * Tipo de DTE según SII de Chile.
 */
export type DteType = '33' | '34' | '39' | '41' | '43' | '45' | '46' | '52' | '56' | '61' | '110' | '111' | '112';

export type DteStatus = 'draft' | 'issued' | 'accepted' | 'rejected' | 'annulled';

export type Currency = 'CLP' | 'USD';

export type ExpenseStatus = 'draft' | 'submitted' | 'approved' | 'paid' | 'rejected';

export type AccountingAccount = {
    id: Uuid;
    tenant_id: Uuid;
    /**
     * Código contable, por ejemplo 1110101.
     */
    code: string;
    name: string;
    account_type: AccountType;
    is_active: boolean;
    created_at: DateTime;
    updated_at: DateTime;
};

export type AccountingAccountCreate = {
    code: string;
    name: string;
    account_type: AccountType;
};

export type AccountingAccountUpdate = {
    code?: string;
    name?: string;
    account_type?: AccountType;
    is_active?: boolean;
};

export type AccountingAccountPage = PageMeta & {
    items: Array<AccountingAccount>;
};

/**
 * Línea de asiento contable de partida doble.
 * Regla de negocio: Principio XOR: o bien debit > 0 o credit > 0, nunca ambos simultáneamente mayores a 0.
 *
 */
export type JournalLine = {
    account_id: Uuid;
    /**
     * Monto al Debe. Si credit > 0, este valor debe ser "0.00".
     */
    debit: NonNegativeDecimalString;
    /**
     * Monto al Haber. Si debit > 0, este valor debe ser "0.00".
     */
    credit: NonNegativeDecimalString;
    memo?: string;
};

/**
 * Datos para crear una línea de asiento contable.
 * Regla de negocio: Principio XOR: o bien debit > 0 o credit > 0, nunca ambos simultáneamente mayores a 0.
 *
 */
export type JournalLineCreate = {
    account_id: Uuid;
    /**
     * Monto al Debe. Si credit > 0, este valor debe ser "0.00".
     */
    debit: NonNegativeDecimalString;
    /**
     * Monto al Haber. Si debit > 0, este valor debe ser "0.00".
     */
    credit: NonNegativeDecimalString;
    memo?: string;
};

export type JournalEntry = {
    id: Uuid;
    tenant_id: Uuid;
    entry_date: _Date;
    description: string;
    status: JournalStatus;
    lines: Array<JournalLine>;
    total_debit: NonNegativeDecimalString;
    total_credit: NonNegativeDecimalString;
    posted_at?: DateTime;
    created_at: DateTime;
    updated_at: DateTime;
};

export type JournalEntryCreate = {
    entry_date: _Date;
    description: string;
    lines: Array<JournalLineCreate>;
};

export type JournalEntryPage = PageMeta & {
    items: Array<JournalEntry>;
};

export type DteInvoice = {
    id: Uuid;
    tenant_id: Uuid;
    dte_type: DteType;
    folio: number;
    issue_date: _Date;
    status: DteStatus;
    currency: Currency;
    recipient_rut?: ChileanRut;
    recipient_name?: string;
    subtotal?: NonNegativeDecimalString;
    tax_amount?: NonNegativeDecimalString;
    total: NonNegativeDecimalString;
    /**
     * URI interna o externa del acuse/recibo SII, cuando exista.
     */
    sii_receipt_uri?: string;
    created_at: DateTime;
    updated_at: DateTime;
};

export type DteInvoiceCreate = {
    dte_type: DteType;
    folio: number;
    issue_date: _Date;
    currency?: Currency;
    recipient_rut?: ChileanRut;
    recipient_name?: string;
    subtotal?: NonNegativeDecimalString;
    tax_amount?: NonNegativeDecimalString;
    total: NonNegativeDecimalString;
};

export type DteInvoicePage = PageMeta & {
    items: Array<DteInvoice>;
};

export type Expense = {
    id: Uuid;
    tenant_id: Uuid;
    expense_date: _Date;
    amount: NonNegativeDecimalString;
    currency: Currency;
    status: ExpenseStatus;
    document_id?: Uuid;
    description?: string;
    merchant?: string;
    created_at: DateTime;
    updated_at: DateTime;
};

export type ExpenseCreate = {
    expense_date: _Date;
    amount: NonNegativeDecimalString;
    currency: Currency;
    document_id?: Uuid;
    description?: string;
    merchant?: string;
};

export type ExpenseUpdate = {
    status?: ExpenseStatus;
    document_id?: Uuid;
    description?: string;
    merchant?: string;
};

export type ExpensePage = PageMeta & {
    items: Array<Expense>;
};

export type Document = {
    id: Uuid;
    tenant_id: Uuid;
    filename: string;
    mime_type: string;
    size_bytes: number;
    checksum_sha256?: string;
    /**
     * Ruta relativa al base URL del API v1 para descargar el contenido.
     */
    content_path: string;
    /**
     * URI interna de almacenamiento. No debe exponer secretos.
     */
    storage_uri?: string;
    created_at: DateTime;
};

export type DocumentUploadRequest = {
    file: Blob | File;
    filename?: string;
    mime_type?: string;
    checksum_sha256?: string;
};

export type DocumentPage = PageMeta & {
    items: Array<Document>;
};

/**
 * Identificador del tenant actual.
 *
 * En desarrollo se envía manualmente.
 * En producción debe validarse contra autenticación y membresías.
 * El cliente nunca debe enviar tenant_id en el body de creación.
 *
 */
export type TenantIdHeader = Uuid;

/**
 * Clave opcional para evitar duplicidad en operaciones POST.
 * Recomendada para creación de gastos, DTE y asientos contables.
 *
 */
export type IdempotencyKey = string;

/**
 * Página solicitada, basada en 1.
 */
export type Page = number;

/**
 * Tamaño de página.
 */
export type PageSize = number;

/**
 * Identificador de cuenta contable.
 */
export type AccountId = Uuid;

/**
 * Identificador de asiento contable.
 */
export type EntryId = Uuid;

/**
 * Identificador de DTE.
 */
export type DteId = Uuid;

/**
 * Identificador de gasto.
 */
export type ExpenseId = Uuid;

/**
 * Identificador de documento.
 */
export type DocumentId = Uuid;

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthErrors = {
    /**
     * Error inesperado.
     */
    default: ProblemDetail;
};

export type GetHealthError = GetHealthErrors[keyof GetHealthErrors];

export type GetHealthResponses = {
    /**
     * Servicio saludable
     */
    200: HealthResponse;
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type ListAccountingAccountsData = {
    body?: never;
    headers: {
        /**
         * Identificador del tenant actual.
         *
         * En desarrollo se envía manualmente.
         * En producción debe validarse contra autenticación y membresías.
         * El cliente nunca debe enviar tenant_id en el body de creación.
         *
         */
        'X-Tenant-ID': Uuid;
    };
    path?: never;
    query?: {
        /**
         * Página solicitada, basada en 1.
         */
        page?: number;
        /**
         * Tamaño de página.
         */
        page_size?: number;
    };
    url: '/accounting/accounts';
};

export type ListAccountingAccountsErrors = {
    /**
     * Error inesperado.
     */
    default: ProblemDetail;
};

export type ListAccountingAccountsError = ListAccountingAccountsErrors[keyof ListAccountingAccountsErrors];

export type ListAccountingAccountsResponses = {
    /**
     * Lista paginada de cuentas contables
     */
    200: AccountingAccountPage;
};

export type ListAccountingAccountsResponse = ListAccountingAccountsResponses[keyof ListAccountingAccountsResponses];

export type CreateAccountingAccountData = {
    body: AccountingAccountCreate;
    headers: {
        /**
         * Identificador del tenant actual.
         *
         * En desarrollo se envía manualmente.
         * En producción debe validarse contra autenticación y membresías.
         * El cliente nunca debe enviar tenant_id en el body de creación.
         *
         */
        'X-Tenant-ID': Uuid;
        /**
         * Clave opcional para evitar duplicidad en operaciones POST.
         * Recomendada para creación de gastos, DTE y asientos contables.
         *
         */
        'Idempotency-Key'?: string;
    };
    path?: never;
    query?: never;
    url: '/accounting/accounts';
};

export type CreateAccountingAccountErrors = {
    /**
     * Solicitud inválida.
     */
    400: ProblemDetail;
    /**
     * Conflicto de estado o duplicidad.
     */
    409: ProblemDetail;
    /**
     * Error de validación semántica.
     */
    422: ProblemDetail;
    /**
     * Error inesperado.
     */
    default: ProblemDetail;
};

export type CreateAccountingAccountError = CreateAccountingAccountErrors[keyof CreateAccountingAccountErrors];

export type CreateAccountingAccountResponses = {
    /**
     * Cuenta contable creada
     */
    201: AccountingAccount;
};

export type CreateAccountingAccountResponse = CreateAccountingAccountResponses[keyof CreateAccountingAccountResponses];

export type GetAccountingAccountData = {
    body?: never;
    headers: {
        /**
         * Identificador del tenant actual.
         *
         * En desarrollo se envía manualmente.
         * En producción debe validarse contra autenticación y membresías.
         * El cliente nunca debe enviar tenant_id en el body de creación.
         *
         */
        'X-Tenant-ID': Uuid;
    };
    path: {
        /**
         * Identificador de cuenta contable.
         */
        accountId: Uuid;
    };
    query?: never;
    url: '/accounting/accounts/{accountId}';
};

export type GetAccountingAccountErrors = {
    /**
     * Recurso no encontrado.
     */
    404: ProblemDetail;
    /**
     * Error inesperado.
     */
    default: ProblemDetail;
};

export type GetAccountingAccountError = GetAccountingAccountErrors[keyof GetAccountingAccountErrors];

export type GetAccountingAccountResponses = {
    /**
     * Cuenta contable
     */
    200: AccountingAccount;
};

export type GetAccountingAccountResponse = GetAccountingAccountResponses[keyof GetAccountingAccountResponses];

export type UpdateAccountingAccountData = {
    body: AccountingAccountUpdate;
    headers: {
        /**
         * Identificador del tenant actual.
         *
         * En desarrollo se envía manualmente.
         * En producción debe validarse contra autenticación y membresías.
         * El cliente nunca debe enviar tenant_id en el body de creación.
         *
         */
        'X-Tenant-ID': Uuid;
    };
    path: {
        /**
         * Identificador de cuenta contable.
         */
        accountId: Uuid;
    };
    query?: never;
    url: '/accounting/accounts/{accountId}';
};

export type UpdateAccountingAccountErrors = {
    /**
     * Solicitud inválida.
     */
    400: ProblemDetail;
    /**
     * Recurso no encontrado.
     */
    404: ProblemDetail;
    /**
     * Conflicto de estado o duplicidad.
     */
    409: ProblemDetail;
    /**
     * Error de validación semántica.
     */
    422: ProblemDetail;
    /**
     * Error inesperado.
     */
    default: ProblemDetail;
};

export type UpdateAccountingAccountError = UpdateAccountingAccountErrors[keyof UpdateAccountingAccountErrors];

export type UpdateAccountingAccountResponses = {
    /**
     * Cuenta contable actualizada
     */
    200: AccountingAccount;
};

export type UpdateAccountingAccountResponse = UpdateAccountingAccountResponses[keyof UpdateAccountingAccountResponses];

export type ListJournalEntriesData = {
    body?: never;
    headers: {
        /**
         * Identificador del tenant actual.
         *
         * En desarrollo se envía manualmente.
         * En producción debe validarse contra autenticación y membresías.
         * El cliente nunca debe enviar tenant_id en el body de creación.
         *
         */
        'X-Tenant-ID': Uuid;
    };
    path?: never;
    query?: {
        /**
         * Página solicitada, basada en 1.
         */
        page?: number;
        /**
         * Tamaño de página.
         */
        page_size?: number;
    };
    url: '/accounting/journal-entries';
};

export type ListJournalEntriesErrors = {
    /**
     * Error inesperado.
     */
    default: ProblemDetail;
};

export type ListJournalEntriesError = ListJournalEntriesErrors[keyof ListJournalEntriesErrors];

export type ListJournalEntriesResponses = {
    /**
     * Lista paginada de asientos contables
     */
    200: JournalEntryPage;
};

export type ListJournalEntriesResponse = ListJournalEntriesResponses[keyof ListJournalEntriesResponses];

export type CreateJournalEntryData = {
    body: JournalEntryCreate;
    headers: {
        /**
         * Identificador del tenant actual.
         *
         * En desarrollo se envía manualmente.
         * En producción debe validarse contra autenticación y membresías.
         * El cliente nunca debe enviar tenant_id en el body de creación.
         *
         */
        'X-Tenant-ID': Uuid;
        /**
         * Clave opcional para evitar duplicidad en operaciones POST.
         * Recomendada para creación de gastos, DTE y asientos contables.
         *
         */
        'Idempotency-Key'?: string;
    };
    path?: never;
    query?: never;
    url: '/accounting/journal-entries';
};

export type CreateJournalEntryErrors = {
    /**
     * Solicitud inválida.
     */
    400: ProblemDetail;
    /**
     * Conflicto de estado o duplicidad.
     */
    409: ProblemDetail;
    /**
     * Error de validación semántica.
     */
    422: ProblemDetail;
    /**
     * Error inesperado.
     */
    default: ProblemDetail;
};

export type CreateJournalEntryError = CreateJournalEntryErrors[keyof CreateJournalEntryErrors];

export type CreateJournalEntryResponses = {
    /**
     * Asiento contable creado
     */
    201: JournalEntry;
};

export type CreateJournalEntryResponse = CreateJournalEntryResponses[keyof CreateJournalEntryResponses];

export type GetJournalEntryData = {
    body?: never;
    headers: {
        /**
         * Identificador del tenant actual.
         *
         * En desarrollo se envía manualmente.
         * En producción debe validarse contra autenticación y membresías.
         * El cliente nunca debe enviar tenant_id en el body de creación.
         *
         */
        'X-Tenant-ID': Uuid;
    };
    path: {
        /**
         * Identificador de asiento contable.
         */
        entryId: Uuid;
    };
    query?: never;
    url: '/accounting/journal-entries/{entryId}';
};

export type GetJournalEntryErrors = {
    /**
     * Recurso no encontrado.
     */
    404: ProblemDetail;
    /**
     * Error inesperado.
     */
    default: ProblemDetail;
};

export type GetJournalEntryError = GetJournalEntryErrors[keyof GetJournalEntryErrors];

export type GetJournalEntryResponses = {
    /**
     * Asiento contable
     */
    200: JournalEntry;
};

export type GetJournalEntryResponse = GetJournalEntryResponses[keyof GetJournalEntryResponses];

export type PostJournalEntryData = {
    body?: never;
    headers: {
        /**
         * Identificador del tenant actual.
         *
         * En desarrollo se envía manualmente.
         * En producción debe validarse contra autenticación y membresías.
         * El cliente nunca debe enviar tenant_id en el body de creación.
         *
         */
        'X-Tenant-ID': Uuid;
    };
    path: {
        /**
         * Identificador de asiento contable.
         */
        entryId: Uuid;
    };
    query?: never;
    url: '/accounting/journal-entries/{entryId}/post';
};

export type PostJournalEntryErrors = {
    /**
     * Recurso no encontrado.
     */
    404: ProblemDetail;
    /**
     * Conflicto de estado o duplicidad.
     */
    409: ProblemDetail;
    /**
     * Error de validación semántica.
     */
    422: ProblemDetail;
    /**
     * Error inesperado.
     */
    default: ProblemDetail;
};

export type PostJournalEntryError = PostJournalEntryErrors[keyof PostJournalEntryErrors];

export type PostJournalEntryResponses = {
    /**
     * Asiento posteado
     */
    200: JournalEntry;
};

export type PostJournalEntryResponse = PostJournalEntryResponses[keyof PostJournalEntryResponses];

export type ListDteInvoicesData = {
    body?: never;
    headers: {
        /**
         * Identificador del tenant actual.
         *
         * En desarrollo se envía manualmente.
         * En producción debe validarse contra autenticación y membresías.
         * El cliente nunca debe enviar tenant_id en el body de creación.
         *
         */
        'X-Tenant-ID': Uuid;
    };
    path?: never;
    query?: {
        /**
         * Página solicitada, basada en 1.
         */
        page?: number;
        /**
         * Tamaño de página.
         */
        page_size?: number;
    };
    url: '/invoicing/dte';
};

export type ListDteInvoicesErrors = {
    /**
     * Error inesperado.
     */
    default: ProblemDetail;
};

export type ListDteInvoicesError = ListDteInvoicesErrors[keyof ListDteInvoicesErrors];

export type ListDteInvoicesResponses = {
    /**
     * Lista paginada de DTE
     */
    200: DteInvoicePage;
};

export type ListDteInvoicesResponse = ListDteInvoicesResponses[keyof ListDteInvoicesResponses];

export type CreateDteInvoiceData = {
    body: DteInvoiceCreate;
    headers: {
        /**
         * Identificador del tenant actual.
         *
         * En desarrollo se envía manualmente.
         * En producción debe validarse contra autenticación y membresías.
         * El cliente nunca debe enviar tenant_id en el body de creación.
         *
         */
        'X-Tenant-ID': Uuid;
        /**
         * Clave opcional para evitar duplicidad en operaciones POST.
         * Recomendada para creación de gastos, DTE y asientos contables.
         *
         */
        'Idempotency-Key'?: string;
    };
    path?: never;
    query?: never;
    url: '/invoicing/dte';
};

export type CreateDteInvoiceErrors = {
    /**
     * Solicitud inválida.
     */
    400: ProblemDetail;
    /**
     * Conflicto de estado o duplicidad.
     */
    409: ProblemDetail;
    /**
     * Error de validación semántica.
     */
    422: ProblemDetail;
    /**
     * Error inesperado.
     */
    default: ProblemDetail;
};

export type CreateDteInvoiceError = CreateDteInvoiceErrors[keyof CreateDteInvoiceErrors];

export type CreateDteInvoiceResponses = {
    /**
     * DTE registrado
     */
    201: DteInvoice;
};

export type CreateDteInvoiceResponse = CreateDteInvoiceResponses[keyof CreateDteInvoiceResponses];

export type GetDteInvoiceData = {
    body?: never;
    headers: {
        /**
         * Identificador del tenant actual.
         *
         * En desarrollo se envía manualmente.
         * En producción debe validarse contra autenticación y membresías.
         * El cliente nunca debe enviar tenant_id en el body de creación.
         *
         */
        'X-Tenant-ID': Uuid;
    };
    path: {
        /**
         * Identificador de DTE.
         */
        dteId: Uuid;
    };
    query?: never;
    url: '/invoicing/dte/{dteId}';
};

export type GetDteInvoiceErrors = {
    /**
     * Recurso no encontrado.
     */
    404: ProblemDetail;
    /**
     * Error inesperado.
     */
    default: ProblemDetail;
};

export type GetDteInvoiceError = GetDteInvoiceErrors[keyof GetDteInvoiceErrors];

export type GetDteInvoiceResponses = {
    /**
     * DTE
     */
    200: DteInvoice;
};

export type GetDteInvoiceResponse = GetDteInvoiceResponses[keyof GetDteInvoiceResponses];

export type IssueDteInvoiceData = {
    body?: never;
    headers: {
        /**
         * Identificador del tenant actual.
         *
         * En desarrollo se envía manualmente.
         * En producción debe validarse contra autenticación y membresías.
         * El cliente nunca debe enviar tenant_id en el body de creación.
         *
         */
        'X-Tenant-ID': Uuid;
    };
    path: {
        /**
         * Identificador de DTE.
         */
        dteId: Uuid;
    };
    query?: never;
    url: '/invoicing/dte/{dteId}/issue';
};

export type IssueDteInvoiceErrors = {
    /**
     * Recurso no encontrado.
     */
    404: ProblemDetail;
    /**
     * Conflicto de estado o duplicidad.
     */
    409: ProblemDetail;
    /**
     * Error de validación semántica.
     */
    422: ProblemDetail;
    /**
     * Error inesperado.
     */
    default: ProblemDetail;
};

export type IssueDteInvoiceError = IssueDteInvoiceErrors[keyof IssueDteInvoiceErrors];

export type IssueDteInvoiceResponses = {
    /**
     * DTE emitido
     */
    200: DteInvoice;
};

export type IssueDteInvoiceResponse = IssueDteInvoiceResponses[keyof IssueDteInvoiceResponses];

export type ListExpensesData = {
    body?: never;
    headers: {
        /**
         * Identificador del tenant actual.
         *
         * En desarrollo se envía manualmente.
         * En producción debe validarse contra autenticación y membresías.
         * El cliente nunca debe enviar tenant_id en el body de creación.
         *
         */
        'X-Tenant-ID': Uuid;
    };
    path?: never;
    query?: {
        /**
         * Página solicitada, basada en 1.
         */
        page?: number;
        /**
         * Tamaño de página.
         */
        page_size?: number;
    };
    url: '/expenses';
};

export type ListExpensesErrors = {
    /**
     * Error inesperado.
     */
    default: ProblemDetail;
};

export type ListExpensesError = ListExpensesErrors[keyof ListExpensesErrors];

export type ListExpensesResponses = {
    /**
     * Lista paginada de gastos
     */
    200: ExpensePage;
};

export type ListExpensesResponse = ListExpensesResponses[keyof ListExpensesResponses];

export type CreateExpenseData = {
    body: ExpenseCreate;
    headers: {
        /**
         * Identificador del tenant actual.
         *
         * En desarrollo se envía manualmente.
         * En producción debe validarse contra autenticación y membresías.
         * El cliente nunca debe enviar tenant_id en el body de creación.
         *
         */
        'X-Tenant-ID': Uuid;
        /**
         * Clave opcional para evitar duplicidad en operaciones POST.
         * Recomendada para creación de gastos, DTE y asientos contables.
         *
         */
        'Idempotency-Key'?: string;
    };
    path?: never;
    query?: never;
    url: '/expenses';
};

export type CreateExpenseErrors = {
    /**
     * Solicitud inválida.
     */
    400: ProblemDetail;
    /**
     * Conflicto de estado o duplicidad.
     */
    409: ProblemDetail;
    /**
     * Error de validación semántica.
     */
    422: ProblemDetail;
    /**
     * Error inesperado.
     */
    default: ProblemDetail;
};

export type CreateExpenseError = CreateExpenseErrors[keyof CreateExpenseErrors];

export type CreateExpenseResponses = {
    /**
     * Gasto creado
     */
    201: Expense;
};

export type CreateExpenseResponse = CreateExpenseResponses[keyof CreateExpenseResponses];

export type GetExpenseData = {
    body?: never;
    headers: {
        /**
         * Identificador del tenant actual.
         *
         * En desarrollo se envía manualmente.
         * En producción debe validarse contra autenticación y membresías.
         * El cliente nunca debe enviar tenant_id en el body de creación.
         *
         */
        'X-Tenant-ID': Uuid;
    };
    path: {
        /**
         * Identificador de gasto.
         */
        expenseId: Uuid;
    };
    query?: never;
    url: '/expenses/{expenseId}';
};

export type GetExpenseErrors = {
    /**
     * Recurso no encontrado.
     */
    404: ProblemDetail;
    /**
     * Error inesperado.
     */
    default: ProblemDetail;
};

export type GetExpenseError = GetExpenseErrors[keyof GetExpenseErrors];

export type GetExpenseResponses = {
    /**
     * Gasto
     */
    200: Expense;
};

export type GetExpenseResponse = GetExpenseResponses[keyof GetExpenseResponses];

export type UpdateExpenseData = {
    body: ExpenseUpdate;
    headers: {
        /**
         * Identificador del tenant actual.
         *
         * En desarrollo se envía manualmente.
         * En producción debe validarse contra autenticación y membresías.
         * El cliente nunca debe enviar tenant_id en el body de creación.
         *
         */
        'X-Tenant-ID': Uuid;
    };
    path: {
        /**
         * Identificador de gasto.
         */
        expenseId: Uuid;
    };
    query?: never;
    url: '/expenses/{expenseId}';
};

export type UpdateExpenseErrors = {
    /**
     * Solicitud inválida.
     */
    400: ProblemDetail;
    /**
     * Recurso no encontrado.
     */
    404: ProblemDetail;
    /**
     * Conflicto de estado o duplicidad.
     */
    409: ProblemDetail;
    /**
     * Error de validación semántica.
     */
    422: ProblemDetail;
    /**
     * Error inesperado.
     */
    default: ProblemDetail;
};

export type UpdateExpenseError = UpdateExpenseErrors[keyof UpdateExpenseErrors];

export type UpdateExpenseResponses = {
    /**
     * Gasto actualizado
     */
    200: Expense;
};

export type UpdateExpenseResponse = UpdateExpenseResponses[keyof UpdateExpenseResponses];

export type ListDocumentsData = {
    body?: never;
    headers: {
        /**
         * Identificador del tenant actual.
         *
         * En desarrollo se envía manualmente.
         * En producción debe validarse contra autenticación y membresías.
         * El cliente nunca debe enviar tenant_id en el body de creación.
         *
         */
        'X-Tenant-ID': Uuid;
    };
    path?: never;
    query?: {
        /**
         * Página solicitada, basada en 1.
         */
        page?: number;
        /**
         * Tamaño de página.
         */
        page_size?: number;
    };
    url: '/documents';
};

export type ListDocumentsErrors = {
    /**
     * Error inesperado.
     */
    default: ProblemDetail;
};

export type ListDocumentsError = ListDocumentsErrors[keyof ListDocumentsErrors];

export type ListDocumentsResponses = {
    /**
     * Lista paginada de documentos
     */
    200: DocumentPage;
};

export type ListDocumentsResponse = ListDocumentsResponses[keyof ListDocumentsResponses];

export type CreateDocumentData = {
    body: DocumentUploadRequest;
    headers: {
        /**
         * Identificador del tenant actual.
         *
         * En desarrollo se envía manualmente.
         * En producción debe validarse contra autenticación y membresías.
         * El cliente nunca debe enviar tenant_id en el body de creación.
         *
         */
        'X-Tenant-ID': Uuid;
        /**
         * Clave opcional para evitar duplicidad en operaciones POST.
         * Recomendada para creación de gastos, DTE y asientos contables.
         *
         */
        'Idempotency-Key'?: string;
    };
    path?: never;
    query?: never;
    url: '/documents';
};

export type CreateDocumentErrors = {
    /**
     * Solicitud inválida.
     */
    400: ProblemDetail;
    /**
     * Conflicto de estado o duplicidad.
     */
    409: ProblemDetail;
    /**
     * Error de validación semántica.
     */
    422: ProblemDetail;
    /**
     * Error inesperado.
     */
    default: ProblemDetail;
};

export type CreateDocumentError = CreateDocumentErrors[keyof CreateDocumentErrors];

export type CreateDocumentResponses = {
    /**
     * Documento creado
     */
    201: Document;
};

export type CreateDocumentResponse = CreateDocumentResponses[keyof CreateDocumentResponses];

export type GetDocumentData = {
    body?: never;
    headers: {
        /**
         * Identificador del tenant actual.
         *
         * En desarrollo se envía manualmente.
         * En producción debe validarse contra autenticación y membresías.
         * El cliente nunca debe enviar tenant_id en el body de creación.
         *
         */
        'X-Tenant-ID': Uuid;
    };
    path: {
        /**
         * Identificador de documento.
         */
        documentId: Uuid;
    };
    query?: never;
    url: '/documents/{documentId}';
};

export type GetDocumentErrors = {
    /**
     * Recurso no encontrado.
     */
    404: ProblemDetail;
    /**
     * Error inesperado.
     */
    default: ProblemDetail;
};

export type GetDocumentError = GetDocumentErrors[keyof GetDocumentErrors];

export type GetDocumentResponses = {
    /**
     * Documento
     */
    200: Document;
};

export type GetDocumentResponse = GetDocumentResponses[keyof GetDocumentResponses];

export type GetDocumentContentData = {
    body?: never;
    headers: {
        /**
         * Identificador del tenant actual.
         *
         * En desarrollo se envía manualmente.
         * En producción debe validarse contra autenticación y membresías.
         * El cliente nunca debe enviar tenant_id en el body de creación.
         *
         */
        'X-Tenant-ID': Uuid;
    };
    path: {
        /**
         * Identificador de documento.
         */
        documentId: Uuid;
    };
    query?: never;
    url: '/documents/{documentId}/content';
};

export type GetDocumentContentErrors = {
    /**
     * Recurso no encontrado.
     */
    404: ProblemDetail;
    /**
     * Error inesperado.
     */
    default: ProblemDetail;
};

export type GetDocumentContentError = GetDocumentContentErrors[keyof GetDocumentContentErrors];

export type GetDocumentContentResponses = {
    /**
     * Contenido binario del documento
     */
    200: Blob | File;
};

export type GetDocumentContentResponse = GetDocumentContentResponses[keyof GetDocumentContentResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:8000/api/v1' | (string & {});
};