/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounting/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar cuentas contables */
        get: operations["listAccountingAccounts"];
        put?: never;
        /** Crear cuenta contable */
        post: operations["createAccountingAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounting/accounts/{accountId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador de cuenta contable. */
                accountId: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        /** Obtener cuenta contable */
        get: operations["getAccountingAccount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Actualizar cuenta contable */
        patch: operations["updateAccountingAccount"];
        trace?: never;
    };
    "/accounting/journal-entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar asientos contables */
        get: operations["listJournalEntries"];
        put?: never;
        /**
         * Crear asiento contable
         * @description Crea un asiento en estado draft.
         *
         *     El backend debe validar que la suma de débitos sea igual a la suma de créditos.
         */
        post: operations["createJournalEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounting/journal-entries/{entryId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador de asiento contable. */
                entryId: components["parameters"]["EntryId"];
            };
            cookie?: never;
        };
        /** Obtener asiento contable */
        get: operations["getJournalEntry"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounting/journal-entries/{entryId}/post": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador de asiento contable. */
                entryId: components["parameters"]["EntryId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Postear asiento contable
         * @description Cambia un asiento de draft a posted.
         *
         *     Solo debe permitirse si el asiento está balanceado.
         */
        post: operations["postJournalEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invoicing/dte": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar DTE */
        get: operations["listDteInvoices"];
        put?: never;
        /**
         * Registrar DTE
         * @description Registra un DTE interno en estado draft.
         *
         *     La emisión real ante SII se gestiona mediante el endpoint de issue.
         */
        post: operations["createDteInvoice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invoicing/dte/{dteId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador de DTE. */
                dteId: components["parameters"]["DteId"];
            };
            cookie?: never;
        };
        /** Obtener DTE */
        get: operations["getDteInvoice"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invoicing/dte/{dteId}/issue": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador de DTE. */
                dteId: components["parameters"]["DteId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Emitir DTE
         * @description Marca el DTE como emitido.
         *
         *     En fases posteriores, este endpoint integrará SII.
         */
        post: operations["issueDteInvoice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/expenses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar gastos */
        get: operations["listExpenses"];
        put?: never;
        /** Crear gasto */
        post: operations["createExpense"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/expenses/{expenseId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador de gasto. */
                expenseId: components["parameters"]["ExpenseId"];
            };
            cookie?: never;
        };
        /** Obtener gasto */
        get: operations["getExpense"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Actualizar gasto */
        patch: operations["updateExpense"];
        trace?: never;
    };
    "/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar documentos */
        get: operations["listDocuments"];
        put?: never;
        /**
         * Subir documento
         * @description Sube un documento binario y registra sus metadatos.
         *
         *     Usar multipart/form-data.
         */
        post: operations["createDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{documentId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador de documento. */
                documentId: components["parameters"]["DocumentId"];
            };
            cookie?: never;
        };
        /** Obtener metadatos de documento */
        get: operations["getDocument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{documentId}/content": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador de documento. */
                documentId: components["parameters"]["DocumentId"];
            };
            cookie?: never;
        };
        /** Descargar contenido de documento */
        get: operations["getDocumentContent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Format: uuid */
        Uuid: string;
        /** Format: date */
        Date: string;
        /** Format: date-time */
        DateTime: string;
        /** @description Número decimal enviado como string para evitar errores de punto flotante. Hasta 2 decimales. */
        DecimalString: string;
        /** @description Número decimal no negativo enviado como string. Hasta 2 decimales. */
        NonNegativeDecimalString: string;
        HealthResponse: {
            /** @enum {string} */
            status: "ok";
            service: string;
            version: string;
        };
        PageMeta: {
            page: number;
            page_size: number;
            total: number;
            total_pages: number;
        };
        ErrorDetail: {
            field: string;
            message: string;
            code?: string;
        };
        ProblemDetail: {
            /** Format: uri */
            type?: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            errors?: components["schemas"]["ErrorDetail"][];
        };
        /** @enum {string} */
        AccountType: "asset" | "liability" | "equity" | "income" | "expense";
        /** @enum {string} */
        JournalStatus: "draft" | "posted" | "voided";
        /**
         * @description Tipo de DTE según SII de Chile.
         * @enum {string}
         */
        DteType: "33" | "34" | "39" | "41" | "43" | "45" | "46" | "52" | "56" | "61" | "110" | "111" | "112";
        /** @enum {string} */
        DteStatus: "draft" | "issued" | "accepted" | "rejected" | "annulled";
        /** @enum {string} */
        Currency: "CLP" | "USD";
        /** @enum {string} */
        ExpenseStatus: "draft" | "submitted" | "approved" | "paid" | "rejected";
        AccountingAccount: {
            id: components["schemas"]["Uuid"];
            tenant_id: components["schemas"]["Uuid"];
            /** @description Código contable, por ejemplo 1110101. */
            code: string;
            name: string;
            account_type: components["schemas"]["AccountType"];
            is_active: boolean;
            created_at: components["schemas"]["DateTime"];
            updated_at: components["schemas"]["DateTime"];
        };
        AccountingAccountCreate: {
            code: string;
            name: string;
            account_type: components["schemas"]["AccountType"];
        };
        AccountingAccountUpdate: {
            code?: string;
            name?: string;
            account_type?: components["schemas"]["AccountType"];
            is_active?: boolean;
        };
        AccountingAccountPage: components["schemas"]["PageMeta"] & {
            items: components["schemas"]["AccountingAccount"][];
        };
        JournalLine: {
            account_id: components["schemas"]["Uuid"];
            debit: components["schemas"]["NonNegativeDecimalString"];
            credit: components["schemas"]["NonNegativeDecimalString"];
            memo?: string;
        };
        JournalLineCreate: {
            account_id: components["schemas"]["Uuid"];
            debit: components["schemas"]["NonNegativeDecimalString"];
            credit: components["schemas"]["NonNegativeDecimalString"];
            memo?: string;
        };
        JournalEntry: {
            id: components["schemas"]["Uuid"];
            tenant_id: components["schemas"]["Uuid"];
            entry_date: components["schemas"]["Date"];
            description: string;
            status: components["schemas"]["JournalStatus"];
            lines: components["schemas"]["JournalLine"][];
            total_debit: components["schemas"]["NonNegativeDecimalString"];
            total_credit: components["schemas"]["NonNegativeDecimalString"];
            posted_at?: components["schemas"]["DateTime"];
            created_at: components["schemas"]["DateTime"];
            updated_at: components["schemas"]["DateTime"];
        };
        JournalEntryCreate: {
            entry_date: components["schemas"]["Date"];
            description: string;
            lines: components["schemas"]["JournalLineCreate"][];
        };
        JournalEntryPage: components["schemas"]["PageMeta"] & {
            items: components["schemas"]["JournalEntry"][];
        };
        DteInvoice: {
            id: components["schemas"]["Uuid"];
            tenant_id: components["schemas"]["Uuid"];
            dte_type: components["schemas"]["DteType"];
            folio: number;
            issue_date: components["schemas"]["Date"];
            status: components["schemas"]["DteStatus"];
            currency: components["schemas"]["Currency"];
            recipient_rut?: string;
            recipient_name?: string;
            subtotal?: components["schemas"]["NonNegativeDecimalString"];
            tax_amount?: components["schemas"]["NonNegativeDecimalString"];
            total: components["schemas"]["NonNegativeDecimalString"];
            /** @description URI interna o externa del acuse/recibo SII, cuando exista. */
            sii_receipt_uri?: string;
            created_at: components["schemas"]["DateTime"];
            updated_at: components["schemas"]["DateTime"];
        };
        DteInvoiceCreate: {
            dte_type: components["schemas"]["DteType"];
            folio: number;
            issue_date: components["schemas"]["Date"];
            /** @default CLP */
            currency: components["schemas"]["Currency"];
            recipient_rut?: string;
            recipient_name?: string;
            subtotal?: components["schemas"]["NonNegativeDecimalString"];
            tax_amount?: components["schemas"]["NonNegativeDecimalString"];
            total: components["schemas"]["NonNegativeDecimalString"];
        };
        DteInvoicePage: components["schemas"]["PageMeta"] & {
            items: components["schemas"]["DteInvoice"][];
        };
        Expense: {
            id: components["schemas"]["Uuid"];
            tenant_id: components["schemas"]["Uuid"];
            expense_date: components["schemas"]["Date"];
            amount: components["schemas"]["NonNegativeDecimalString"];
            currency: components["schemas"]["Currency"];
            status: components["schemas"]["ExpenseStatus"];
            document_id?: components["schemas"]["Uuid"];
            description?: string;
            merchant?: string;
            created_at: components["schemas"]["DateTime"];
            updated_at: components["schemas"]["DateTime"];
        };
        ExpenseCreate: {
            expense_date: components["schemas"]["Date"];
            amount: components["schemas"]["NonNegativeDecimalString"];
            currency: components["schemas"]["Currency"];
            document_id?: components["schemas"]["Uuid"];
            description?: string;
            merchant?: string;
        };
        ExpenseUpdate: {
            status?: components["schemas"]["ExpenseStatus"];
            document_id?: components["schemas"]["Uuid"];
            description?: string;
            merchant?: string;
        };
        ExpensePage: components["schemas"]["PageMeta"] & {
            items: components["schemas"]["Expense"][];
        };
        Document: {
            id: components["schemas"]["Uuid"];
            tenant_id: components["schemas"]["Uuid"];
            filename: string;
            mime_type: string;
            size_bytes: number;
            checksum_sha256?: string;
            /**
             * @description Ruta relativa al base URL del API v1 para descargar el contenido.
             * @example /documents/00000000-0000-0000-0000-000000000000/content
             */
            content_path: string;
            /** @description URI interna de almacenamiento. No debe exponer secretos. */
            storage_uri?: string;
            created_at: components["schemas"]["DateTime"];
        };
        DocumentUploadRequest: {
            /** Format: binary */
            file: string;
            filename?: string;
            mime_type?: string;
            checksum_sha256?: string;
        };
        DocumentPage: components["schemas"]["PageMeta"] & {
            items: components["schemas"]["Document"][];
        };
    };
    responses: {
        /** @description Solicitud inválida. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description No autenticado. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Sin permiso para el tenant o recurso. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Recurso no encontrado. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Conflicto de estado o duplicidad. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Error de validación semántica. */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Error inesperado. */
        UnexpectedError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ProblemDetail"];
            };
        };
    };
    parameters: {
        /**
         * @description Identificador del tenant actual.
         *
         *     En desarrollo se envía manualmente.
         *     En producción debe validarse contra autenticación y membresías.
         *     El cliente nunca debe enviar tenant_id en el body de creación.
         */
        TenantIdHeader: components["schemas"]["Uuid"];
        /**
         * @description Clave opcional para evitar duplicidad en operaciones POST.
         *     Recomendada para creación de gastos, DTE y asientos contables.
         */
        IdempotencyKey: string;
        /** @description Página solicitada, basada en 1. */
        Page: number;
        /** @description Tamaño de página. */
        PageSize: number;
        /** @description Identificador de cuenta contable. */
        AccountId: components["schemas"]["Uuid"];
        /** @description Identificador de asiento contable. */
        EntryId: components["schemas"]["Uuid"];
        /** @description Identificador de DTE. */
        DteId: components["schemas"]["Uuid"];
        /** @description Identificador de gasto. */
        ExpenseId: components["schemas"]["Uuid"];
        /** @description Identificador de documento. */
        DocumentId: components["schemas"]["Uuid"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Servicio saludable */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            default: components["responses"]["UnexpectedError"];
        };
    };
    listAccountingAccounts: {
        parameters: {
            query?: {
                /** @description Página solicitada, basada en 1. */
                page?: components["parameters"]["Page"];
                /** @description Tamaño de página. */
                page_size?: components["parameters"]["PageSize"];
            };
            header: {
                /**
                 * @description Identificador del tenant actual.
                 *
                 *     En desarrollo se envía manualmente.
                 *     En producción debe validarse contra autenticación y membresías.
                 *     El cliente nunca debe enviar tenant_id en el body de creación.
                 */
                "X-Tenant-ID": components["parameters"]["TenantIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista paginada de cuentas contables */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountingAccountPage"];
                };
            };
            default: components["responses"]["UnexpectedError"];
        };
    };
    createAccountingAccount: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Identificador del tenant actual.
                 *
                 *     En desarrollo se envía manualmente.
                 *     En producción debe validarse contra autenticación y membresías.
                 *     El cliente nunca debe enviar tenant_id en el body de creación.
                 */
                "X-Tenant-ID": components["parameters"]["TenantIdHeader"];
                /**
                 * @description Clave opcional para evitar duplicidad en operaciones POST.
                 *     Recomendada para creación de gastos, DTE y asientos contables.
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountingAccountCreate"];
            };
        };
        responses: {
            /** @description Cuenta contable creada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountingAccount"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            default: components["responses"]["UnexpectedError"];
        };
    };
    getAccountingAccount: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Identificador del tenant actual.
                 *
                 *     En desarrollo se envía manualmente.
                 *     En producción debe validarse contra autenticación y membresías.
                 *     El cliente nunca debe enviar tenant_id en el body de creación.
                 */
                "X-Tenant-ID": components["parameters"]["TenantIdHeader"];
            };
            path: {
                /** @description Identificador de cuenta contable. */
                accountId: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cuenta contable */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountingAccount"];
                };
            };
            404: components["responses"]["NotFound"];
            default: components["responses"]["UnexpectedError"];
        };
    };
    updateAccountingAccount: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Identificador del tenant actual.
                 *
                 *     En desarrollo se envía manualmente.
                 *     En producción debe validarse contra autenticación y membresías.
                 *     El cliente nunca debe enviar tenant_id en el body de creación.
                 */
                "X-Tenant-ID": components["parameters"]["TenantIdHeader"];
            };
            path: {
                /** @description Identificador de cuenta contable. */
                accountId: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountingAccountUpdate"];
            };
        };
        responses: {
            /** @description Cuenta contable actualizada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountingAccount"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            default: components["responses"]["UnexpectedError"];
        };
    };
    listJournalEntries: {
        parameters: {
            query?: {
                /** @description Página solicitada, basada en 1. */
                page?: components["parameters"]["Page"];
                /** @description Tamaño de página. */
                page_size?: components["parameters"]["PageSize"];
            };
            header: {
                /**
                 * @description Identificador del tenant actual.
                 *
                 *     En desarrollo se envía manualmente.
                 *     En producción debe validarse contra autenticación y membresías.
                 *     El cliente nunca debe enviar tenant_id en el body de creación.
                 */
                "X-Tenant-ID": components["parameters"]["TenantIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista paginada de asientos contables */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalEntryPage"];
                };
            };
            default: components["responses"]["UnexpectedError"];
        };
    };
    createJournalEntry: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Identificador del tenant actual.
                 *
                 *     En desarrollo se envía manualmente.
                 *     En producción debe validarse contra autenticación y membresías.
                 *     El cliente nunca debe enviar tenant_id en el body de creación.
                 */
                "X-Tenant-ID": components["parameters"]["TenantIdHeader"];
                /**
                 * @description Clave opcional para evitar duplicidad en operaciones POST.
                 *     Recomendada para creación de gastos, DTE y asientos contables.
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JournalEntryCreate"];
            };
        };
        responses: {
            /** @description Asiento contable creado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalEntry"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            default: components["responses"]["UnexpectedError"];
        };
    };
    getJournalEntry: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Identificador del tenant actual.
                 *
                 *     En desarrollo se envía manualmente.
                 *     En producción debe validarse contra autenticación y membresías.
                 *     El cliente nunca debe enviar tenant_id en el body de creación.
                 */
                "X-Tenant-ID": components["parameters"]["TenantIdHeader"];
            };
            path: {
                /** @description Identificador de asiento contable. */
                entryId: components["parameters"]["EntryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Asiento contable */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalEntry"];
                };
            };
            404: components["responses"]["NotFound"];
            default: components["responses"]["UnexpectedError"];
        };
    };
    postJournalEntry: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Identificador del tenant actual.
                 *
                 *     En desarrollo se envía manualmente.
                 *     En producción debe validarse contra autenticación y membresías.
                 *     El cliente nunca debe enviar tenant_id en el body de creación.
                 */
                "X-Tenant-ID": components["parameters"]["TenantIdHeader"];
            };
            path: {
                /** @description Identificador de asiento contable. */
                entryId: components["parameters"]["EntryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Asiento posteado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalEntry"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            default: components["responses"]["UnexpectedError"];
        };
    };
    listDteInvoices: {
        parameters: {
            query?: {
                /** @description Página solicitada, basada en 1. */
                page?: components["parameters"]["Page"];
                /** @description Tamaño de página. */
                page_size?: components["parameters"]["PageSize"];
            };
            header: {
                /**
                 * @description Identificador del tenant actual.
                 *
                 *     En desarrollo se envía manualmente.
                 *     En producción debe validarse contra autenticación y membresías.
                 *     El cliente nunca debe enviar tenant_id en el body de creación.
                 */
                "X-Tenant-ID": components["parameters"]["TenantIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista paginada de DTE */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DteInvoicePage"];
                };
            };
            default: components["responses"]["UnexpectedError"];
        };
    };
    createDteInvoice: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Identificador del tenant actual.
                 *
                 *     En desarrollo se envía manualmente.
                 *     En producción debe validarse contra autenticación y membresías.
                 *     El cliente nunca debe enviar tenant_id en el body de creación.
                 */
                "X-Tenant-ID": components["parameters"]["TenantIdHeader"];
                /**
                 * @description Clave opcional para evitar duplicidad en operaciones POST.
                 *     Recomendada para creación de gastos, DTE y asientos contables.
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DteInvoiceCreate"];
            };
        };
        responses: {
            /** @description DTE registrado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DteInvoice"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            default: components["responses"]["UnexpectedError"];
        };
    };
    getDteInvoice: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Identificador del tenant actual.
                 *
                 *     En desarrollo se envía manualmente.
                 *     En producción debe validarse contra autenticación y membresías.
                 *     El cliente nunca debe enviar tenant_id en el body de creación.
                 */
                "X-Tenant-ID": components["parameters"]["TenantIdHeader"];
            };
            path: {
                /** @description Identificador de DTE. */
                dteId: components["parameters"]["DteId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description DTE */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DteInvoice"];
                };
            };
            404: components["responses"]["NotFound"];
            default: components["responses"]["UnexpectedError"];
        };
    };
    issueDteInvoice: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Identificador del tenant actual.
                 *
                 *     En desarrollo se envía manualmente.
                 *     En producción debe validarse contra autenticación y membresías.
                 *     El cliente nunca debe enviar tenant_id en el body de creación.
                 */
                "X-Tenant-ID": components["parameters"]["TenantIdHeader"];
            };
            path: {
                /** @description Identificador de DTE. */
                dteId: components["parameters"]["DteId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description DTE emitido */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DteInvoice"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            default: components["responses"]["UnexpectedError"];
        };
    };
    listExpenses: {
        parameters: {
            query?: {
                /** @description Página solicitada, basada en 1. */
                page?: components["parameters"]["Page"];
                /** @description Tamaño de página. */
                page_size?: components["parameters"]["PageSize"];
            };
            header: {
                /**
                 * @description Identificador del tenant actual.
                 *
                 *     En desarrollo se envía manualmente.
                 *     En producción debe validarse contra autenticación y membresías.
                 *     El cliente nunca debe enviar tenant_id en el body de creación.
                 */
                "X-Tenant-ID": components["parameters"]["TenantIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista paginada de gastos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpensePage"];
                };
            };
            default: components["responses"]["UnexpectedError"];
        };
    };
    createExpense: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Identificador del tenant actual.
                 *
                 *     En desarrollo se envía manualmente.
                 *     En producción debe validarse contra autenticación y membresías.
                 *     El cliente nunca debe enviar tenant_id en el body de creación.
                 */
                "X-Tenant-ID": components["parameters"]["TenantIdHeader"];
                /**
                 * @description Clave opcional para evitar duplicidad en operaciones POST.
                 *     Recomendada para creación de gastos, DTE y asientos contables.
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpenseCreate"];
            };
        };
        responses: {
            /** @description Gasto creado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Expense"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            default: components["responses"]["UnexpectedError"];
        };
    };
    getExpense: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Identificador del tenant actual.
                 *
                 *     En desarrollo se envía manualmente.
                 *     En producción debe validarse contra autenticación y membresías.
                 *     El cliente nunca debe enviar tenant_id en el body de creación.
                 */
                "X-Tenant-ID": components["parameters"]["TenantIdHeader"];
            };
            path: {
                /** @description Identificador de gasto. */
                expenseId: components["parameters"]["ExpenseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Gasto */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Expense"];
                };
            };
            404: components["responses"]["NotFound"];
            default: components["responses"]["UnexpectedError"];
        };
    };
    updateExpense: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Identificador del tenant actual.
                 *
                 *     En desarrollo se envía manualmente.
                 *     En producción debe validarse contra autenticación y membresías.
                 *     El cliente nunca debe enviar tenant_id en el body de creación.
                 */
                "X-Tenant-ID": components["parameters"]["TenantIdHeader"];
            };
            path: {
                /** @description Identificador de gasto. */
                expenseId: components["parameters"]["ExpenseId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpenseUpdate"];
            };
        };
        responses: {
            /** @description Gasto actualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Expense"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            default: components["responses"]["UnexpectedError"];
        };
    };
    listDocuments: {
        parameters: {
            query?: {
                /** @description Página solicitada, basada en 1. */
                page?: components["parameters"]["Page"];
                /** @description Tamaño de página. */
                page_size?: components["parameters"]["PageSize"];
            };
            header: {
                /**
                 * @description Identificador del tenant actual.
                 *
                 *     En desarrollo se envía manualmente.
                 *     En producción debe validarse contra autenticación y membresías.
                 *     El cliente nunca debe enviar tenant_id en el body de creación.
                 */
                "X-Tenant-ID": components["parameters"]["TenantIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista paginada de documentos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentPage"];
                };
            };
            default: components["responses"]["UnexpectedError"];
        };
    };
    createDocument: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Identificador del tenant actual.
                 *
                 *     En desarrollo se envía manualmente.
                 *     En producción debe validarse contra autenticación y membresías.
                 *     El cliente nunca debe enviar tenant_id en el body de creación.
                 */
                "X-Tenant-ID": components["parameters"]["TenantIdHeader"];
                /**
                 * @description Clave opcional para evitar duplicidad en operaciones POST.
                 *     Recomendada para creación de gastos, DTE y asientos contables.
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["DocumentUploadRequest"];
            };
        };
        responses: {
            /** @description Documento creado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            default: components["responses"]["UnexpectedError"];
        };
    };
    getDocument: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Identificador del tenant actual.
                 *
                 *     En desarrollo se envía manualmente.
                 *     En producción debe validarse contra autenticación y membresías.
                 *     El cliente nunca debe enviar tenant_id en el body de creación.
                 */
                "X-Tenant-ID": components["parameters"]["TenantIdHeader"];
            };
            path: {
                /** @description Identificador de documento. */
                documentId: components["parameters"]["DocumentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Documento */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            404: components["responses"]["NotFound"];
            default: components["responses"]["UnexpectedError"];
        };
    };
    getDocumentContent: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Identificador del tenant actual.
                 *
                 *     En desarrollo se envía manualmente.
                 *     En producción debe validarse contra autenticación y membresías.
                 *     El cliente nunca debe enviar tenant_id en el body de creación.
                 */
                "X-Tenant-ID": components["parameters"]["TenantIdHeader"];
            };
            path: {
                /** @description Identificador de documento. */
                documentId: components["parameters"]["DocumentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Contenido binario del documento */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            404: components["responses"]["NotFound"];
            default: components["responses"]["UnexpectedError"];
        };
    };
}
