/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check del servicio */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounting/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar cuentas contables */
        get: operations["listAccountingAccounts"];
        put?: never;
        /** Crear cuenta contable */
        post: operations["createAccountingAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounting/accounts/seed-default": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inicializar plan de cuentas chileno */
        post: operations["seedDefaultAccountingAccounts"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounting/journal-entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar asientos de diario */
        get: operations["listJournalEntries"];
        put?: never;
        /** Crear asiento contable en draft */
        post: operations["createJournalEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounting/journal-entries/{id}/post": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publicar y asentar definitivamente un asiento (Debe = Haber) */
        post: operations["postJournalEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounting/journal-entries/{id}/void": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Anular asiento contable */
        post: operations["voidJournalEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invoicing/dte": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar DTEs emitidos */
        get: operations["listDtes"];
        put?: never;
        /** Crear DTE interno */
        post: operations["createDte"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invoicing/dte/{id}/emit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transmitir DTE al SII */
        post: operations["emitDte"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/expenses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar gastos */
        get: operations["listExpenses"];
        put?: never;
        /** Crear gasto con desglose de insumos */
        post: operations["createExpense"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/expenses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle del gasto e insumos */
        get: operations["getExpenseById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/expenses/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Aprobar gasto */
        post: operations["approveExpense"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/expenses/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rechazar gasto */
        post: operations["rejectExpense"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Subir factura, boleta o comprobante a la bóveda multi-tenant */
        post: operations["uploadDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metadatos del documento */
        get: operations["getDocumentMetadata"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Descargar binario físico del documento */
        get: operations["downloadDocument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/ingredients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar insumos */
        get: operations["listIngredients"];
        put?: never;
        /** Crear insumo */
        post: operations["createIngredient"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/production/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar escandallos */
        get: operations["listRecipes"];
        put?: never;
        /** Crear escandallo */
        post: operations["createRecipe"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/production/costing/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cálculo de costo y margen bruto */
        get: operations["getProductCosting"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/production/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar órdenes de horneado */
        get: operations["listProductionOrders"];
        put?: never;
        /** Crear orden de horneado con descuento de inventario */
        post: operations["createProductionOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @example ok */
            status: string;
            /** @example pasteleria-api-fase1 */
            service: string;
            /** Format: date-time */
            timestamp: string;
            /** @example default-atelier */
            tenant_id: string;
        };
        ErrorResponse: {
            error: string;
            message: string;
            statusCode: number;
        };
        Account: {
            /** Format: uuid */
            id: string;
            tenant_id: string;
            /** @example 1.1.01 */
            codigo: string;
            /** @example Caja Chica y Efectivo */
            nombre: string;
            /** @enum {string} */
            tipo: "activo" | "pasivo" | "patrimonio" | "ingreso" | "gasto";
            /** @default true */
            activa: boolean;
        };
        AccountCreateInput: {
            codigo: string;
            nombre: string;
            /** @enum {string} */
            tipo: "activo" | "pasivo" | "patrimonio" | "ingreso" | "gasto";
        };
        JournalItem: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            entry_id: string;
            /** Format: uuid */
            account_id: string;
            debe: number;
            haber: number;
            contacto_rut_o_nombre?: string | null;
        };
        JournalItemInput: {
            /** Format: uuid */
            account_id: string;
            debe: number;
            haber: number;
            contacto_rut_o_nombre?: string | null;
        };
        JournalEntry: {
            /** Format: uuid */
            id: string;
            tenant_id: string;
            numero_asiento: number;
            /** Format: date */
            fecha_asiento: string;
            glosa_descripcion: string;
            /** @enum {string} */
            estado: "draft" | "posted" | "voided";
            /** @example MANUAL */
            referencia_origen: string;
            items: components["schemas"]["JournalItem"][];
            /** Format: date-time */
            created_at: string;
        };
        JournalEntryCreateInput: {
            /** Format: date */
            fecha_asiento: string;
            glosa_descripcion: string;
            /** @default MANUAL */
            referencia_origen: string;
            items: components["schemas"]["JournalItemInput"][];
        };
        DTE: {
            /** Format: uuid */
            id: string;
            tenant_id: string;
            /** @enum {integer} */
            tipo_dte: 33 | 39 | 61;
            folio: number;
            /** Format: date */
            fecha_emision: string;
            emisor_rut: string;
            receptor_rut: string;
            receptor_razon_social: string;
            monto_neto: number;
            monto_exento: number;
            monto_iva: number;
            monto_total: number;
            /** @enum {string} */
            estado_sii: "draft" | "generated" | "sent_to_sii" | "accepted_by_sii" | "rejected_by_sii";
            track_id_sii?: string | null;
            xml_payload_uri?: string | null;
            order_id?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        DTECreateInput: {
            /** @enum {integer} */
            tipo_dte: 33 | 39 | 61;
            folio?: number | null;
            /** Format: date */
            fecha_emision: string;
            emisor_rut: string;
            receptor_rut: string;
            receptor_razon_social: string;
            monto_neto: number;
            /** @default 0 */
            monto_exento: number;
            monto_iva?: number;
            monto_total: number;
            order_id?: string | null;
        };
        ExpenseItemDetail: {
            /** Format: uuid */
            id: string;
            ingredient_id?: string | null;
            /** @example Harina de Trigo Seleccionada */
            nombre_insumo: string;
            /** @example 25 */
            cantidad: number;
            /** @example kg */
            unidad_medida: string;
            /** @example 1200 */
            precio_unitario: number;
            /** @example 30000 */
            subtotal: number;
        };
        ExpenseItemDetailInput: {
            ingredient_id?: string | null;
            nombre_insumo: string;
            cantidad: number;
            unidad_medida: string;
            precio_unitario: number;
        };
        Expense: {
            /** Format: uuid */
            id: string;
            tenant_id: string;
            folio_comprobante?: string | null;
            proveedor_nombre: string;
            proveedor_rut?: string | null;
            /** Format: date */
            fecha_gasto: string;
            monto_neto: number;
            monto_iva: number;
            monto_total: number;
            /** @default CLP */
            moneda: string;
            /** @enum {string} */
            categoria_gasto: "materias_primas" | "packaging" | "servicios" | "arriendo" | "otros";
            /** @enum {string} */
            metodo_pago: "transferencia" | "efectivo" | "tarjeta_credito";
            /** @enum {string} */
            estado: "draft" | "pending_approval" | "approved" | "rejected";
            document_id?: string | null;
            insumos_detalle?: components["schemas"]["ExpenseItemDetail"][];
            created_by_user_id: string;
            approved_by_user_id?: string | null;
            motivo_rechazo?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        ExpenseCreateInput: {
            folio_comprobante?: string | null;
            proveedor_nombre: string;
            proveedor_rut?: string | null;
            /** Format: date */
            fecha_gasto: string;
            monto_neto: number;
            /** @default 0 */
            monto_iva: number;
            monto_total: number;
            /** @default CLP */
            moneda: string;
            /**
             * @default materias_primas
             * @enum {string}
             */
            categoria_gasto: "materias_primas" | "packaging" | "servicios" | "arriendo" | "otros";
            /**
             * @default transferencia
             * @enum {string}
             */
            metodo_pago: "transferencia" | "efectivo" | "tarjeta_credito";
            document_id?: string | null;
            insumos_detalle?: components["schemas"]["ExpenseItemDetailInput"][];
        };
        ExpenseRejectInput: {
            motivo_rechazo: string;
        };
        DocumentMetadata: {
            /** Format: uuid */
            id: string;
            tenant_id: string;
            filename_original: string;
            mime_type: string;
            file_size_bytes: number;
            storage_uri: string;
            checksum_sha256: string;
            uploaded_by_user_id: string;
            /** Format: date-time */
            created_at: string;
        };
        Ingredient: {
            /** Format: uuid */
            id: string;
            tenant_id: string;
            codigo?: string | null;
            /** @example Mantequilla Francesa sin sal 82% MG */
            nombre: string;
            /** @enum {string} */
            unidad_medida: "kg" | "g" | "l" | "ml" | "unidad";
            /** @example 9200 */
            costo_unitario_promedio: number;
            /** @example 25.5 */
            stock_actual: number;
            alergenos?: string[];
            /** Format: date-time */
            created_at: string;
        };
        IngredientCreateInput: {
            codigo?: string | null;
            nombre: string;
            /** @enum {string} */
            unidad_medida: "kg" | "g" | "l" | "ml" | "unidad";
            costo_unitario_promedio: number;
            /** @default 0 */
            stock_actual: number;
            alergenos?: string[];
        };
        RecipeIngredientItem: {
            /** Format: uuid */
            ingredient_id: string;
            nombre_ingrediente: string;
            cantidad_neta: number;
            unidad_medida: string;
            /** @example 5 */
            porcentaje_merma: number;
            /** @example 2415 */
            costo_calculado: number;
        };
        RecipeIngredientItemInput: {
            /** Format: uuid */
            ingredient_id: string;
            cantidad_neta: number;
            /** @default 0 */
            porcentaje_merma: number;
        };
        RecipePackagingItem: {
            nombre: string;
            costo_unitario: number;
            /** @default 1 */
            cantidad: number;
        };
        Recipe: {
            /** Format: uuid */
            id: string;
            tenant_id: string;
            product_id: string;
            nombre_receta: string;
            rendimiento_porciones: number;
            tiempo_elaboracion_minutos?: number;
            ingredientes: components["schemas"]["RecipeIngredientItem"][];
            empaques: components["schemas"]["RecipePackagingItem"][];
            costo_total_batch: number;
            costo_por_porcion: number;
            instrucciones?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        RecipeCreateInput: {
            product_id: string;
            nombre_receta: string;
            rendimiento_porciones: number;
            /** @default 60 */
            tiempo_elaboracion_minutos: number;
            ingredientes: components["schemas"]["RecipeIngredientItemInput"][];
            empaques?: components["schemas"]["RecipePackagingItem"][];
            instrucciones?: string | null;
        };
        ProductCostingAnalysis: {
            product_id: string;
            tenant_id: string;
            nombre_producto: string;
            precio_venta_neto: number;
            costo_insumos_porcion: number;
            costo_empaque_porcion: number;
            costo_total_porcion: number;
            margen_bruto_monto: number;
            margen_bruto_porcentaje: number;
            alerta_margen_bajo?: boolean;
            /** Format: date-time */
            fecha_calculo: string;
        };
        ProductionOrder: {
            /** Format: uuid */
            id: string;
            tenant_id: string;
            numero_orden: string;
            /** Format: uuid */
            recipe_id: string;
            product_id: string;
            cantidad_a_elaborar: number;
            /** @enum {string} */
            estado: "scheduled" | "in_prep" | "baking" | "finished" | "cancelled";
            /** Format: date */
            fecha_programada: string;
            /** Format: date-time */
            fecha_finalizada?: string | null;
            responsable_chef?: string | null;
            inventario_descontado: boolean;
            notas?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        ProductionOrderCreateInput: {
            /** Format: uuid */
            recipe_id: string;
            cantidad_a_elaborar: number;
            /** Format: date */
            fecha_programada: string;
            responsable_chef?: string | null;
            /** @default true */
            descontar_inventario_inmediato: boolean;
            notas?: string | null;
        };
    };
    responses: never;
    parameters: {
        /** @description Identificador de la pastelería/tenant */
        TenantIdHeader: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Estado del backend y tenant */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    listAccountingAccounts: {
        parameters: {
            query?: never;
            header?: {
                /** @description Identificador de la pastelería/tenant */
                "X-Tenant-ID"?: components["parameters"]["TenantIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de cuentas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"][];
                };
            };
        };
    };
    createAccountingAccount: {
        parameters: {
            query?: never;
            header?: {
                /** @description Identificador de la pastelería/tenant */
                "X-Tenant-ID"?: components["parameters"]["TenantIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountCreateInput"];
            };
        };
        responses: {
            /** @description Cuenta creada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
        };
    };
    seedDefaultAccountingAccounts: {
        parameters: {
            query?: never;
            header?: {
                /** @description Identificador de la pastelería/tenant */
                "X-Tenant-ID"?: components["parameters"]["TenantIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cuentas inicializadas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"][];
                };
            };
        };
    };
    listJournalEntries: {
        parameters: {
            query?: {
                estado?: "draft" | "posted" | "voided";
                fechaDesde?: string;
                fechaHasta?: string;
            };
            header?: {
                /** @description Identificador de la pastelería/tenant */
                "X-Tenant-ID"?: components["parameters"]["TenantIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de asientos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalEntry"][];
                };
            };
        };
    };
    createJournalEntry: {
        parameters: {
            query?: never;
            header?: {
                /** @description Identificador de la pastelería/tenant */
                "X-Tenant-ID"?: components["parameters"]["TenantIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JournalEntryCreateInput"];
            };
        };
        responses: {
            /** @description Asiento creado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalEntry"];
                };
            };
            /** @description Error partida doble */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    postJournalEntry: {
        parameters: {
            query?: never;
            header?: {
                /** @description Identificador de la pastelería/tenant */
                "X-Tenant-ID"?: components["parameters"]["TenantIdHeader"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Asiento contabilizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalEntry"];
                };
            };
        };
    };
    voidJournalEntry: {
        parameters: {
            query?: never;
            header?: {
                /** @description Identificador de la pastelería/tenant */
                "X-Tenant-ID"?: components["parameters"]["TenantIdHeader"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Asiento anulado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalEntry"];
                };
            };
        };
    };
    listDtes: {
        parameters: {
            query?: {
                tipoDte?: 33 | 39 | 61;
                estadoSii?: "draft" | "generated" | "sent_to_sii" | "accepted_by_sii" | "rejected_by_sii";
            };
            header?: {
                /** @description Identificador de la pastelería/tenant */
                "X-Tenant-ID"?: components["parameters"]["TenantIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Listado de DTEs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DTE"][];
                };
            };
        };
    };
    createDte: {
        parameters: {
            query?: never;
            header?: {
                /** @description Identificador de la pastelería/tenant */
                "X-Tenant-ID"?: components["parameters"]["TenantIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DTECreateInput"];
            };
        };
        responses: {
            /** @description DTE creado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DTE"];
                };
            };
        };
    };
    emitDte: {
        parameters: {
            query?: never;
            header?: {
                /** @description Identificador de la pastelería/tenant */
                "X-Tenant-ID"?: components["parameters"]["TenantIdHeader"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description DTE emitido */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DTE"];
                };
            };
        };
    };
    listExpenses: {
        parameters: {
            query?: {
                estado?: "draft" | "pending_approval" | "approved" | "rejected";
                categoria?: string;
            };
            header?: {
                /** @description Identificador de la pastelería/tenant */
                "X-Tenant-ID"?: components["parameters"]["TenantIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de gastos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Expense"][];
                };
            };
        };
    };
    createExpense: {
        parameters: {
            query?: never;
            header?: {
                /** @description Identificador de la pastelería/tenant */
                "X-Tenant-ID"?: components["parameters"]["TenantIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpenseCreateInput"];
            };
        };
        responses: {
            /** @description Gasto registrado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Expense"];
                };
            };
        };
    };
    getExpenseById: {
        parameters: {
            query?: never;
            header?: {
                /** @description Identificador de la pastelería/tenant */
                "X-Tenant-ID"?: components["parameters"]["TenantIdHeader"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Detalle del gasto */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Expense"];
                };
            };
        };
    };
    approveExpense: {
        parameters: {
            query?: never;
            header?: {
                /** @description Identificador de la pastelería/tenant */
                "X-Tenant-ID"?: components["parameters"]["TenantIdHeader"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Gasto aprobado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Expense"];
                };
            };
        };
    };
    rejectExpense: {
        parameters: {
            query?: never;
            header?: {
                /** @description Identificador de la pastelería/tenant */
                "X-Tenant-ID"?: components["parameters"]["TenantIdHeader"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpenseRejectInput"];
            };
        };
        responses: {
            /** @description Gasto rechazado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Expense"];
                };
            };
        };
    };
    uploadDocument: {
        parameters: {
            query?: never;
            header?: {
                /** @description Identificador de la pastelería/tenant */
                "X-Tenant-ID"?: components["parameters"]["TenantIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description Archivo PDF, PNG, JPG o WEBP (máx. 10 MB)
                     */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Archivo almacenado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentMetadata"];
                };
            };
            /** @description Error formato o tamaño */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getDocumentMetadata: {
        parameters: {
            query?: never;
            header?: {
                /** @description Identificador de la pastelería/tenant */
                "X-Tenant-ID"?: components["parameters"]["TenantIdHeader"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Metadata obtenida */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentMetadata"];
                };
            };
        };
    };
    downloadDocument: {
        parameters: {
            query?: never;
            header?: {
                /** @description Identificador de la pastelería/tenant */
                "X-Tenant-ID"?: components["parameters"]["TenantIdHeader"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Flujo binario */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
        };
    };
    listIngredients: {
        parameters: {
            query?: {
                search?: string;
            };
            header?: {
                /** @description Identificador de la pastelería/tenant */
                "X-Tenant-ID"?: components["parameters"]["TenantIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de insumos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ingredient"][];
                };
            };
        };
    };
    createIngredient: {
        parameters: {
            query?: never;
            header?: {
                /** @description Identificador de la pastelería/tenant */
                "X-Tenant-ID"?: components["parameters"]["TenantIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngredientCreateInput"];
            };
        };
        responses: {
            /** @description Insumo creado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ingredient"];
                };
            };
        };
    };
    listRecipes: {
        parameters: {
            query?: {
                productId?: string;
            };
            header?: {
                /** @description Identificador de la pastelería/tenant */
                "X-Tenant-ID"?: components["parameters"]["TenantIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de recetas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recipe"][];
                };
            };
        };
    };
    createRecipe: {
        parameters: {
            query?: never;
            header?: {
                /** @description Identificador de la pastelería/tenant */
                "X-Tenant-ID"?: components["parameters"]["TenantIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipeCreateInput"];
            };
        };
        responses: {
            /** @description Receta creada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recipe"];
                };
            };
        };
    };
    getProductCosting: {
        parameters: {
            query?: never;
            header?: {
                /** @description Identificador de la pastelería/tenant */
                "X-Tenant-ID"?: components["parameters"]["TenantIdHeader"];
            };
            path: {
                productId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Análisis de costeo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductCostingAnalysis"];
                };
            };
        };
    };
    listProductionOrders: {
        parameters: {
            query?: {
                estado?: "scheduled" | "in_prep" | "baking" | "finished" | "cancelled";
            };
            header?: {
                /** @description Identificador de la pastelería/tenant */
                "X-Tenant-ID"?: components["parameters"]["TenantIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Órdenes de producción */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductionOrder"][];
                };
            };
        };
    };
    createProductionOrder: {
        parameters: {
            query?: never;
            header?: {
                /** @description Identificador de la pastelería/tenant */
                "X-Tenant-ID"?: components["parameters"]["TenantIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductionOrderCreateInput"];
            };
        };
        responses: {
            /** @description Orden creada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductionOrder"];
                };
            };
        };
    };
}
