apis:
  fase1@v1:
    root: ./openapi/fase1.yaml
    x-openapi-ts:
      output: ./packages/shared-types/src/openapi.ts

extends:
  - recommended

rules:
  operation-4xx-response: off
  no-server-example.com: off
  tag-description: off
  info-contact: off
  license-url: off
  operation-operationId-unique: error
  operation-operationId: error
  no-$ref-siblings: error
