/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check del servicio y tenant activo */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounting/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar cuentas contables paginadas */
        get: operations["listAccountingAccounts"];
        put?: never;
        /** Crear cuenta contable */
        post: operations["createAccountingAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounting/accounts/seed-default": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inicializar plan de cuentas chileno por defecto */
        post: operations["seedDefaultAccountingAccounts"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounting/journal-entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar asientos de diario paginados */
        get: operations["listJournalEntries"];
        put?: never;
        /** Crear asiento contable en borrador (requiere balance Debe = Haber) */
        post: operations["createJournalEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounting/journal-entries/{id}/post": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publicar y asentar definitivamente un asiento contable */
        post: operations["postJournalEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounting/journal-entries/{id}/void": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Anular asiento contable */
        post: operations["voidJournalEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invoicing/dte": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar DTEs emitidos paginados */
        get: operations["listDtes"];
        put?: never;
        /** Crear documento tributario electrónico DTE */
        post: operations["createDte"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invoicing/dte/{id}/emit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transmitir DTE al SII */
        post: operations["emitDte"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/expenses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar gastos paginados */
        get: operations["listExpenses"];
        put?: never;
        /** Crear gasto con desglose de insumos */
        post: operations["createExpense"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/expenses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle del gasto e insumos asociados */
        get: operations["getExpenseById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/expenses/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Aprobar gasto e impactar inventario (PPP) */
        post: operations["approveExpense"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/expenses/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rechazar gasto */
        post: operations["rejectExpense"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Subir factura, boleta o comprobante a la bóveda multi-tenant */
        post: operations["uploadDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metadatos del documento en bóveda */
        get: operations["getDocumentMetadata"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Descargar binario físico del documento */
        get: operations["downloadDocument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/ingredients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar insumos paginados */
        get: operations["listIngredients"];
        put?: never;
        /** Crear insumo */
        post: operations["createIngredient"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/production/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar escandallos y fichas técnicas */
        get: operations["listRecipes"];
        put?: never;
        /** Crear escandallo / ficha técnica */
        post: operations["createRecipe"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/production/costing/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cálculo de costo de producción y margen bruto en tiempo real */
        get: operations["getProductCosting"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/production/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar órdenes de horneado paginadas */
        get: operations["listProductionOrders"];
        put?: never;
        /** Crear orden de horneado con descuento de inventario */
        post: operations["createProductionOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Monto monetario no negativo representado como string decimal exacto (hasta 2 decimales) para prevenir errores de precisión flotante.
         * @example 15990.00
         */
        NonNegativeDecimalString: string;
        ProblemDetails: {
            /**
             * Format: uri
             * @description URI de referencia que identifica el tipo de problema (RFC 7807)
             * @example about:blank
             */
            type: string;
            /**
             * @description Resumen corto y legible del error
             * @example Bad Request
             */
            title: string;
            /**
             * @description Código de estado HTTP
             * @example 400
             */
            status: number;
            /**
             * @description Explicación detallada del problema específico ocurrido
             * @example El asiento contable no está cuadrado: Debe (15000.00) != Haber (14000.00)
             */
            detail?: string;
            /**
             * @description URI que identifica la ocurrencia específica del problema
             * @example /api/v1/accounting/journal-entries
             */
            instance?: string;
            /** @description Detalle de errores por campo cuando aplica validación */
            invalid_params?: {
                /** @example monto_neto */
                name: string;
                /** @example Debe coincidir con la expresión ^\\d+(\\.\\d{1,2})?$ */
                reason: string;
            }[];
        };
        PaginationMeta: {
            /**
             * @description Total de registros disponibles
             * @example 42
             */
            total: number;
            /**
             * @description Página actual solicitada
             * @example 1
             */
            page: number;
            /**
             * @description Elementos por página
             * @example 20
             */
            page_size: number;
            /**
             * @description Cantidad total de páginas
             * @example 3
             */
            total_pages: number;
        };
        HealthResponse: {
            /** @example ok */
            status: string;
            /** @example pasteleria-api-fase1 */
            service: string;
            /** Format: date-time */
            timestamp: string;
            /** @example default-atelier */
            tenant_id: string;
        };
        Account: {
            /** Format: uuid */
            id: string;
            tenant_id: string;
            /** @example 1.1.01 */
            codigo: string;
            /** @example Caja Chica y Efectivo */
            nombre: string;
            /** @enum {string} */
            tipo: "activo" | "pasivo" | "patrimonio" | "ingreso" | "gasto";
            /** @default true */
            activa: boolean;
        };
        AccountCreateInput: {
            /** @example 1.1.01 */
            codigo: string;
            /** @example Caja Chica y Efectivo */
            nombre: string;
            /** @enum {string} */
            tipo: "activo" | "pasivo" | "patrimonio" | "ingreso" | "gasto";
        };
        PaginatedAccounts: {
            items: components["schemas"]["Account"][];
            meta: components["schemas"]["PaginationMeta"];
        };
        JournalItem: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            entry_id: string;
            /** Format: uuid */
            account_id: string;
            debe: components["schemas"]["NonNegativeDecimalString"];
            haber: components["schemas"]["NonNegativeDecimalString"];
            /** @example 76.123.456-7 */
            contacto_rut_o_nombre?: string | null;
        };
        JournalItemInput: {
            /** Format: uuid */
            account_id: string;
            debe: components["schemas"]["NonNegativeDecimalString"];
            haber: components["schemas"]["NonNegativeDecimalString"];
            /** @example 76.123.456-7 */
            contacto_rut_o_nombre?: string | null;
        };
        JournalEntry: {
            /** Format: uuid */
            id: string;
            tenant_id: string;
            numero_asiento: number;
            /** Format: date */
            fecha_asiento: string;
            glosa_descripcion: string;
            /** @enum {string} */
            estado: "draft" | "posted" | "voided";
            /** @example MANUAL */
            referencia_origen: string;
            items: components["schemas"]["JournalItem"][];
            /** Format: date-time */
            created_at: string;
        };
        JournalEntryCreateInput: {
            /** Format: date */
            fecha_asiento: string;
            glosa_descripcion: string;
            /** @default MANUAL */
            referencia_origen: string;
            items: components["schemas"]["JournalItemInput"][];
        };
        PaginatedJournalEntries: {
            items: components["schemas"]["JournalEntry"][];
            meta: components["schemas"]["PaginationMeta"];
        };
        DTE: {
            /** Format: uuid */
            id: string;
            tenant_id: string;
            /** @enum {integer} */
            tipo_dte: 33 | 39 | 61;
            folio: number;
            /** Format: date */
            fecha_emision: string;
            /** @example 76.999.888-K */
            emisor_rut: string;
            /** @example 15.432.123-4 */
            receptor_rut: string;
            /** @example Cliente Particular SpA */
            receptor_razon_social: string;
            monto_neto: components["schemas"]["NonNegativeDecimalString"];
            monto_exento: components["schemas"]["NonNegativeDecimalString"];
            monto_iva: components["schemas"]["NonNegativeDecimalString"];
            monto_total: components["schemas"]["NonNegativeDecimalString"];
            /** @enum {string} */
            estado_sii: "draft" | "generated" | "sent_to_sii" | "accepted_by_sii" | "rejected_by_sii";
            /** @example TRACK-889911 */
            track_id_sii?: string | null;
            /** @example vault/dte/33-1024.xml */
            xml_payload_uri?: string | null;
            /** Format: uuid */
            order_id?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        DTECreateInput: {
            /** @enum {integer} */
            tipo_dte: 33 | 39 | 61;
            /** @example 1024 */
            folio?: number | null;
            /** Format: date */
            fecha_emision: string;
            /** @example 76.999.888-K */
            emisor_rut: string;
            /** @example 15.432.123-4 */
            receptor_rut: string;
            /** @example Cliente Particular SpA */
            receptor_razon_social: string;
            monto_neto: components["schemas"]["NonNegativeDecimalString"];
            monto_exento?: components["schemas"]["NonNegativeDecimalString"];
            monto_iva?: components["schemas"]["NonNegativeDecimalString"];
            monto_total: components["schemas"]["NonNegativeDecimalString"];
            /** Format: uuid */
            order_id?: string | null;
        };
        PaginatedDtes: {
            items: components["schemas"]["DTE"][];
            meta: components["schemas"]["PaginationMeta"];
        };
        ExpenseItemDetail: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            ingredient_id?: string | null;
            /** @example Harina de Trigo Seleccionada */
            nombre_insumo: string;
            /** @example 25 */
            cantidad: number;
            /** @example kg */
            unidad_medida: string;
            precio_unitario: components["schemas"]["NonNegativeDecimalString"];
            subtotal: components["schemas"]["NonNegativeDecimalString"];
        };
        ExpenseItemDetailInput: {
            /** Format: uuid */
            ingredient_id?: string | null;
            /** @example Harina de Trigo Seleccionada */
            nombre_insumo: string;
            /** @example 25 */
            cantidad: number;
            /** @example kg */
            unidad_medida: string;
            precio_unitario: components["schemas"]["NonNegativeDecimalString"];
        };
        Expense: {
            /** Format: uuid */
            id: string;
            tenant_id: string;
            /** @example FAC-98442 */
            folio_comprobante?: string | null;
            /** @example Molinos del Sur SpA */
            proveedor_nombre: string;
            /** @example 76.888.777-6 */
            proveedor_rut?: string | null;
            /** Format: date */
            fecha_gasto: string;
            monto_neto: components["schemas"]["NonNegativeDecimalString"];
            monto_iva: components["schemas"]["NonNegativeDecimalString"];
            monto_total: components["schemas"]["NonNegativeDecimalString"];
            /**
             * @default CLP
             * @example CLP
             */
            moneda: string;
            /** @enum {string} */
            categoria_gasto: "materias_primas" | "packaging" | "servicios" | "arriendo" | "otros";
            /** @enum {string} */
            metodo_pago: "transferencia" | "efectivo" | "tarjeta_credito";
            /** @enum {string} */
            estado: "draft" | "pending_approval" | "approved" | "rejected";
            /** Format: uuid */
            document_id?: string | null;
            insumos_detalle?: components["schemas"]["ExpenseItemDetail"][];
            /** @example usr_chef_admin */
            created_by_user_id: string;
            /** @example usr_owner */
            approved_by_user_id?: string | null;
            /** @example Factura sin detalle fiscal adjunto */
            motivo_rechazo?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        ExpenseCreateInput: {
            /** @example FAC-98442 */
            folio_comprobante?: string | null;
            /** @example Molinos del Sur SpA */
            proveedor_nombre: string;
            /** @example 76.888.777-6 */
            proveedor_rut?: string | null;
            /** Format: date */
            fecha_gasto: string;
            monto_neto: components["schemas"]["NonNegativeDecimalString"];
            monto_iva?: components["schemas"]["NonNegativeDecimalString"];
            monto_total: components["schemas"]["NonNegativeDecimalString"];
            /** @default CLP */
            moneda: string;
            /**
             * @default materias_primas
             * @enum {string}
             */
            categoria_gasto: "materias_primas" | "packaging" | "servicios" | "arriendo" | "otros";
            /**
             * @default transferencia
             * @enum {string}
             */
            metodo_pago: "transferencia" | "efectivo" | "tarjeta_credito";
            /** Format: uuid */
            document_id?: string | null;
            insumos_detalle?: components["schemas"]["ExpenseItemDetailInput"][];
        };
        ExpenseRejectInput: {
            /** @example Comprobante no legible */
            motivo_rechazo: string;
        };
        PaginatedExpenses: {
            items: components["schemas"]["Expense"][];
            meta: components["schemas"]["PaginationMeta"];
        };
        DocumentMetadata: {
            /** Format: uuid */
            id: string;
            tenant_id: string;
            /** @example factura_compra_molino.pdf */
            filename_original: string;
            /** @example application/pdf */
            mime_type: string;
            /** @example 1048576 */
            file_size_bytes: number;
            /** @example vault/default-atelier/2026/09/factura.pdf */
            storage_uri: string;
            /** @example e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 */
            checksum_sha256: string;
            /** @example usr_chef_admin */
            uploaded_by_user_id: string;
            /** Format: date-time */
            created_at: string;
        };
        Ingredient: {
            /** Format: uuid */
            id: string;
            tenant_id: string;
            /** @example ING-MAN-01 */
            codigo?: string | null;
            /** @example Mantequilla Francesa sin sal 82% MG */
            nombre: string;
            /** @enum {string} */
            unidad_medida: "kg" | "g" | "l" | "ml" | "unidad";
            costo_unitario_promedio: components["schemas"]["NonNegativeDecimalString"];
            /** @example 25.5 */
            stock_actual: number;
            /**
             * @example [
             *       "Lácteos"
             *     ]
             */
            alergenos?: string[];
            /** Format: date-time */
            created_at: string;
        };
        IngredientCreateInput: {
            /** @example ING-MAN-01 */
            codigo?: string | null;
            /** @example Mantequilla Francesa sin sal 82% MG */
            nombre: string;
            /** @enum {string} */
            unidad_medida: "kg" | "g" | "l" | "ml" | "unidad";
            costo_unitario_promedio: components["schemas"]["NonNegativeDecimalString"];
            /** @default 0 */
            stock_actual: number;
            alergenos?: string[];
        };
        PaginatedIngredients: {
            items: components["schemas"]["Ingredient"][];
            meta: components["schemas"]["PaginationMeta"];
        };
        RecipeIngredientItem: {
            /** Format: uuid */
            ingredient_id: string;
            /** @example Mantequilla Francesa 82% MG */
            nombre_ingrediente: string;
            /** @example 0.25 */
            cantidad_neta: number;
            /** @example kg */
            unidad_medida: string;
            /** @example 5 */
            porcentaje_merma: number;
            costo_calculado: components["schemas"]["NonNegativeDecimalString"];
        };
        RecipeIngredientItemInput: {
            /** Format: uuid */
            ingredient_id: string;
            /** @example 0.25 */
            cantidad_neta: number;
            /**
             * @default 0
             * @example 5
             */
            porcentaje_merma: number;
        };
        RecipePackagingItem: {
            /** @example Caja Premium con cinta de raso */
            nombre: string;
            costo_unitario: components["schemas"]["NonNegativeDecimalString"];
            /**
             * @default 1
             * @example 1
             */
            cantidad: number;
        };
        Recipe: {
            /** Format: uuid */
            id: string;
            tenant_id: string;
            /** @example prod_opera_01 */
            product_id: string;
            /** @example Ópera Clásica de París 12 Porciones */
            nombre_receta: string;
            /** @example 12 */
            rendimiento_porciones: number;
            /** @example 90 */
            tiempo_elaboracion_minutos?: number;
            ingredientes: components["schemas"]["RecipeIngredientItem"][];
            empaques: components["schemas"]["RecipePackagingItem"][];
            costo_total_batch: components["schemas"]["NonNegativeDecimalString"];
            costo_por_porcion: components["schemas"]["NonNegativeDecimalString"];
            /** @example Hornear a 180°C durante 12 minutos. */
            instrucciones?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        RecipeCreateInput: {
            /** @example prod_opera_01 */
            product_id: string;
            /** @example Ópera Clásica de París 12 Porciones */
            nombre_receta: string;
            /** @example 12 */
            rendimiento_porciones: number;
            /** @default 60 */
            tiempo_elaboracion_minutos: number;
            ingredientes: components["schemas"]["RecipeIngredientItemInput"][];
            empaques?: components["schemas"]["RecipePackagingItem"][];
            /** @example Hornear a 180°C durante 12 minutos. */
            instrucciones?: string | null;
        };
        PaginatedRecipes: {
            items: components["schemas"]["Recipe"][];
            meta: components["schemas"]["PaginationMeta"];
        };
        ProductCostingAnalysis: {
            /** @example prod_opera_01 */
            product_id: string;
            tenant_id: string;
            /** @example Torta Ópera 12 Porciones */
            nombre_producto: string;
            precio_venta_neto: components["schemas"]["NonNegativeDecimalString"];
            costo_insumos_porcion: components["schemas"]["NonNegativeDecimalString"];
            costo_empaque_porcion: components["schemas"]["NonNegativeDecimalString"];
            costo_total_porcion: components["schemas"]["NonNegativeDecimalString"];
            margen_bruto_monto: components["schemas"]["NonNegativeDecimalString"];
            /** @example 62.5 */
            margen_bruto_porcentaje: number;
            /** @example false */
            alerta_margen_bajo?: boolean;
            /** Format: date-time */
            fecha_calculo: string;
        };
        ProductionOrder: {
            /** Format: uuid */
            id: string;
            tenant_id: string;
            /** @example ORD-2026-001 */
            numero_orden: string;
            /** Format: uuid */
            recipe_id: string;
            /** @example prod_opera_01 */
            product_id: string;
            /** @example 4 */
            cantidad_a_elaborar: number;
            /** @enum {string} */
            estado: "scheduled" | "in_prep" | "baking" | "finished" | "cancelled";
            /** Format: date */
            fecha_programada: string;
            /** Format: date-time */
            fecha_finalizada?: string | null;
            /** @example Chef Pierre */
            responsable_chef?: string | null;
            /** @example true */
            inventario_descontado: boolean;
            /** @example Decoración con pan de oro comestible */
            notas?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        ProductionOrderCreateInput: {
            /** Format: uuid */
            recipe_id: string;
            /** @example 4 */
            cantidad_a_elaborar: number;
            /** Format: date */
            fecha_programada: string;
            /** @example Chef Pierre */
            responsable_chef?: string | null;
            /** @default true */
            descontar_inventario_inmediato: boolean;
            /** @example Decoración con pan de oro */
            notas?: string | null;
        };
        PaginatedProductionOrders: {
            items: components["schemas"]["ProductionOrder"][];
            meta: components["schemas"]["PaginationMeta"];
        };
    };
    responses: {
        /** @description Solicitud incorrecta o datos inválidos */
        BadRequestError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description No autenticado o token vencido */
        UnauthorizedError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description No autorizado para acceder a este tenant o recurso */
        ForbiddenError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Recurso no encontrado */
        NotFoundError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Error interno del servidor */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: {
        /** @description Identificador obligatorio de la pastelería/tenant */
        TenantIdHeader: string;
        /** @description Clave única de idempotencia para prevenir duplicados en operaciones de creación */
        IdempotencyKeyHeader: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Estado del backend y tenant */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            400: components["responses"]["BadRequestError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listAccountingAccounts: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header: {
                /** @description Identificador obligatorio de la pastelería/tenant */
                "X-Tenant-ID": components["parameters"]["TenantIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista paginada de cuentas contables */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAccounts"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createAccountingAccount: {
        parameters: {
            query?: never;
            header: {
                /** @description Identificador obligatorio de la pastelería/tenant */
                "X-Tenant-ID": components["parameters"]["TenantIdHeader"];
                /** @description Clave única de idempotencia para prevenir duplicados en operaciones de creación */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKeyHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountCreateInput"];
            };
        };
        responses: {
            /** @description Cuenta creada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    seedDefaultAccountingAccounts: {
        parameters: {
            query?: never;
            header: {
                /** @description Identificador obligatorio de la pastelería/tenant */
                "X-Tenant-ID": components["parameters"]["TenantIdHeader"];
                /** @description Clave única de idempotencia para prevenir duplicados en operaciones de creación */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKeyHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cuentas inicializadas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"][];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listJournalEntries: {
        parameters: {
            query?: {
                estado?: "draft" | "posted" | "voided";
                fechaDesde?: string;
                fechaHasta?: string;
                page?: number;
                page_size?: number;
            };
            header: {
                /** @description Identificador obligatorio de la pastelería/tenant */
                "X-Tenant-ID": components["parameters"]["TenantIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista paginada de asientos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedJournalEntries"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createJournalEntry: {
        parameters: {
            query?: never;
            header: {
                /** @description Identificador obligatorio de la pastelería/tenant */
                "X-Tenant-ID": components["parameters"]["TenantIdHeader"];
                /** @description Clave única de idempotencia para prevenir duplicados en operaciones de creación */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKeyHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JournalEntryCreateInput"];
            };
        };
        responses: {
            /** @description Asiento creado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalEntry"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    postJournalEntry: {
        parameters: {
            query?: never;
            header: {
                /** @description Identificador obligatorio de la pastelería/tenant */
                "X-Tenant-ID": components["parameters"]["TenantIdHeader"];
                /** @description Clave única de idempotencia para prevenir duplicados en operaciones de creación */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKeyHeader"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Asiento contabilizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalEntry"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    voidJournalEntry: {
        parameters: {
            query?: never;
            header: {
                /** @description Identificador obligatorio de la pastelería/tenant */
                "X-Tenant-ID": components["parameters"]["TenantIdHeader"];
                /** @description Clave única de idempotencia para prevenir duplicados en operaciones de creación */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKeyHeader"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Asiento anulado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalEntry"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listDtes: {
        parameters: {
            query?: {
                tipoDte?: 33 | 39 | 61;
                estadoSii?: "draft" | "generated" | "sent_to_sii" | "accepted_by_sii" | "rejected_by_sii";
                page?: number;
                page_size?: number;
            };
            header: {
                /** @description Identificador obligatorio de la pastelería/tenant */
                "X-Tenant-ID": components["parameters"]["TenantIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Listado de DTEs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedDtes"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createDte: {
        parameters: {
            query?: never;
            header: {
                /** @description Identificador obligatorio de la pastelería/tenant */
                "X-Tenant-ID": components["parameters"]["TenantIdHeader"];
                /** @description Clave única de idempotencia para prevenir duplicados en operaciones de creación */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKeyHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DTECreateInput"];
            };
        };
        responses: {
            /** @description DTE creado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DTE"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    emitDte: {
        parameters: {
            query?: never;
            header: {
                /** @description Identificador obligatorio de la pastelería/tenant */
                "X-Tenant-ID": components["parameters"]["TenantIdHeader"];
                /** @description Clave única de idempotencia para prevenir duplicados en operaciones de creación */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKeyHeader"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description DTE transmitido */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DTE"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listExpenses: {
        parameters: {
            query?: {
                estado?: "draft" | "pending_approval" | "approved" | "rejected";
                categoria?: string;
                page?: number;
                page_size?: number;
            };
            header: {
                /** @description Identificador obligatorio de la pastelería/tenant */
                "X-Tenant-ID": components["parameters"]["TenantIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista paginada de gastos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedExpenses"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createExpense: {
        parameters: {
            query?: never;
            header: {
                /** @description Identificador obligatorio de la pastelería/tenant */
                "X-Tenant-ID": components["parameters"]["TenantIdHeader"];
                /** @description Clave única de idempotencia para prevenir duplicados en operaciones de creación */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKeyHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpenseCreateInput"];
            };
        };
        responses: {
            /** @description Gasto registrado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Expense"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getExpenseById: {
        parameters: {
            query?: never;
            header: {
                /** @description Identificador obligatorio de la pastelería/tenant */
                "X-Tenant-ID": components["parameters"]["TenantIdHeader"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Detalle del gasto */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Expense"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    approveExpense: {
        parameters: {
            query?: never;
            header: {
                /** @description Identificador obligatorio de la pastelería/tenant */
                "X-Tenant-ID": components["parameters"]["TenantIdHeader"];
                /** @description Clave única de idempotencia para prevenir duplicados en operaciones de creación */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKeyHeader"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Gasto aprobado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Expense"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    rejectExpense: {
        parameters: {
            query?: never;
            header: {
                /** @description Identificador obligatorio de la pastelería/tenant */
                "X-Tenant-ID": components["parameters"]["TenantIdHeader"];
                /** @description Clave única de idempotencia para prevenir duplicados en operaciones de creación */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKeyHeader"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpenseRejectInput"];
            };
        };
        responses: {
            /** @description Gasto rechazado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Expense"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    uploadDocument: {
        parameters: {
            query?: never;
            header: {
                /** @description Identificador obligatorio de la pastelería/tenant */
                "X-Tenant-ID": components["parameters"]["TenantIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description Archivo PDF, PNG, JPG o WEBP (máx. 10 MB)
                     */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Archivo almacenado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentMetadata"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getDocumentMetadata: {
        parameters: {
            query?: never;
            header: {
                /** @description Identificador obligatorio de la pastelería/tenant */
                "X-Tenant-ID": components["parameters"]["TenantIdHeader"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Metadata obtenida */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentMetadata"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    downloadDocument: {
        parameters: {
            query?: never;
            header: {
                /** @description Identificador obligatorio de la pastelería/tenant */
                "X-Tenant-ID": components["parameters"]["TenantIdHeader"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Flujo binario */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listIngredients: {
        parameters: {
            query?: {
                search?: string;
                page?: number;
                page_size?: number;
            };
            header: {
                /** @description Identificador obligatorio de la pastelería/tenant */
                "X-Tenant-ID": components["parameters"]["TenantIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista paginada de insumos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedIngredients"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createIngredient: {
        parameters: {
            query?: never;
            header: {
                /** @description Identificador obligatorio de la pastelería/tenant */
                "X-Tenant-ID": components["parameters"]["TenantIdHeader"];
                /** @description Clave única de idempotencia para prevenir duplicados en operaciones de creación */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKeyHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngredientCreateInput"];
            };
        };
        responses: {
            /** @description Insumo creado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ingredient"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listRecipes: {
        parameters: {
            query?: {
                productId?: string;
                page?: number;
                page_size?: number;
            };
            header: {
                /** @description Identificador obligatorio de la pastelería/tenant */
                "X-Tenant-ID": components["parameters"]["TenantIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista paginada de recetas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedRecipes"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createRecipe: {
        parameters: {
            query?: never;
            header: {
                /** @description Identificador obligatorio de la pastelería/tenant */
                "X-Tenant-ID": components["parameters"]["TenantIdHeader"];
                /** @description Clave única de idempotencia para prevenir duplicados en operaciones de creación */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKeyHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipeCreateInput"];
            };
        };
        responses: {
            /** @description Receta creada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recipe"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getProductCosting: {
        parameters: {
            query?: never;
            header: {
                /** @description Identificador obligatorio de la pastelería/tenant */
                "X-Tenant-ID": components["parameters"]["TenantIdHeader"];
            };
            path: {
                productId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Análisis de costeo y margen bruto */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductCostingAnalysis"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listProductionOrders: {
        parameters: {
            query?: {
                estado?: "scheduled" | "in_prep" | "baking" | "finished" | "cancelled";
                page?: number;
                page_size?: number;
            };
            header: {
                /** @description Identificador obligatorio de la pastelería/tenant */
                "X-Tenant-ID": components["parameters"]["TenantIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista paginada de órdenes de producción */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedProductionOrders"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createProductionOrder: {
        parameters: {
            query?: never;
            header: {
                /** @description Identificador obligatorio de la pastelería/tenant */
                "X-Tenant-ID": components["parameters"]["TenantIdHeader"];
                /** @description Clave única de idempotencia para prevenir duplicados en operaciones de creación */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKeyHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductionOrderCreateInput"];
            };
        };
        responses: {
            /** @description Orden de producción creada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductionOrder"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
