import { Category, Product, Order } from '@pasteleria/shared-types';

export const MOCK_CATEGORIES: Category[] = [
  {
    id: 'cat-pasteles-autor',
    name: 'Pasteles de Autor',
    slug: 'pasteles-de-autor',
    description: 'Creaciones exclusivas de nuestra chef pastelera con ingredientes de origen.',
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80',
    displayOrder: 1,
  },
  {
    id: 'cat-tartas-finas',
    name: 'Tartas Finas',
    slug: 'tartas-finas',
    description: 'Masa sablée crujiente, cremas infusionadas y frutas de estación seleccionadas.',
    image: 'https://images.unsplash.com/photo-1519869325930-281384150729?auto=format&fit=crop&w=800&q=80',
    displayOrder: 2,
  },
  {
    id: 'cat-macarons',
    name: 'Macarons & Petits Fours',
    slug: 'macarons-petits-fours',
    description: 'Delicadeza parisina elaborada con harina de almendras y ganaches infusionadas.',
    image: 'https://images.unsplash.com/photo-1569864321318-64445eb07464?auto=format&fit=crop&w=800&q=80',
    displayOrder: 3,
  },
  {
    id: 'cat-panaderia',
    name: 'Viennoiserie & Panadería',
    slug: 'viennoiserie-panaderia',
    description: 'Croissants de mantequilla francesa pura y masa madre de fermentación lenta.',
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=800&q=80',
    displayOrder: 4,
  },
  {
    id: 'cat-sin-gluten',
    name: 'Línea Saludable & Sin Gluten',
    slug: 'saludable-sin-gluten',
    description: 'Postres libres de gluten y opciones veganas sin comprometer el sabor sublime.',
    image: 'https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?auto=format&fit=crop&w=800&q=80',
    displayOrder: 5,
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-opera-noir',
    name: 'Gâteau Opéra Grand Cru',
    slug: 'gateau-opera-grand-cru',
    tagline: 'Bizcocho Joconde, ganache de chocolate Guanaja 70% y crema de café arábica.',
    description: 'El clásico francés reinterpretado con capas milimétricas de bizcocho Joconde bañado en almíbar de café espresso de especialidad, ganache sedosa de chocolate negro Grand Cru y glaseado espejo.',
    price: 38.0,
    discountedPrice: 34.0,
    categoryId: 'cat-pasteles-autor',
    images: [
      'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?auto=format&fit=crop&w=800&q=80',
    ],
    ingredients: ['Harina de almendras', 'Café arábica de origen', 'Chocolate Valrhona 70%', 'Mantequilla AOP', 'Huevos de campo'],
    allergens: ['Gluten', 'Lácteos', 'Huevos', 'Frutos secos'],
    calories: 420,
    isGlutenFree: false,
    isVegan: false,
    isCustomizable: true,
    rating: 4.9,
    reviewsCount: 128,
    stockStatus: 'in_stock',
    prepTimeMinutes: 45,
    featured: true,
    variants: [
      { id: 'var-op-6p', name: '6 a 8 Porciones', portions: 8, price: 38.0, sku: 'OP-08P', isAvailable: true },
      { id: 'var-op-12p', name: '12 a 14 Porciones', portions: 14, price: 62.0, sku: 'OP-14P', isAvailable: true },
      { id: 'var-op-ind', name: 'Porción Individual', portions: 1, price: 6.5, sku: 'OP-IND', isAvailable: true },
    ],
  },
  {
    id: 'prod-tartaleta-frutos-rojos',
    name: 'Tartelette Framboise & Pistache',
    slug: 'tartelette-framboise-pistache',
    tagline: 'Sablée crocante, crema diplomática de pistacho siciliano y frambuesas frescas.',
    description: 'Base de masa sablée crujiente rellena con crema diplomática ligera infusionada con pasta de pistacho de Bronte DOP, coronada con frambuesas silvestres frescas y lluvia de pistachos tostados.',
    price: 29.5,
    categoryId: 'cat-tartas-finas',
    images: [
      'https://images.unsplash.com/photo-1519869325930-281384150729?auto=format&fit=crop&w=800&q=80',
    ],
    ingredients: ['Frambuesas frescas', 'Pistachos de Sicilia', 'Mantequilla francesa', 'Vainilla Bourbon de Madagascar'],
    allergens: ['Gluten', 'Lácteos', 'Huevos', 'Pistacho'],
    calories: 340,
    isGlutenFree: false,
    isVegan: false,
    isCustomizable: false,
    rating: 4.8,
    reviewsCount: 94,
    stockStatus: 'in_stock',
    prepTimeMinutes: 30,
    featured: true,
    variants: [
      { id: 'var-tf-6p', name: 'Mediana (6 porciones)', portions: 6, price: 29.5, sku: 'TF-06P', isAvailable: true },
      { id: 'var-tf-ind', name: 'Individual', portions: 1, price: 5.8, sku: 'TF-IND', isAvailable: true },
    ],
  },
  {
    id: 'prod-macarons-prestige',
    name: 'Coffret Prestige 12 Macarons',
    slug: 'coffret-prestige-macarons',
    tagline: 'Selección de autor: Vainilla Bourbon, Maracuyá, Caramelo Salado, Pistacho y Frambuesa.',
    description: 'Caja de regalo de lujo con 12 macarons artesanales elaborados con almendras de California, merengue italiano impecable y rellenos cremosos sin conservantes.',
    price: 24.0,
    categoryId: 'cat-macarons',
    images: [
      'https://images.unsplash.com/photo-1569864321318-64445eb07464?auto=format&fit=crop&w=800&q=80',
    ],
    ingredients: ['Harina de almendra fina', 'Claras de huevo pasteurizadas', 'Chocolate blanco y negro', 'Frutas naturales'],
    allergens: ['Huevos', 'Lácteos', 'Frutos secos (Almendra, Pistacho)'],
    calories: 95,
    isGlutenFree: true,
    isVegan: false,
    isCustomizable: true,
    rating: 5.0,
    reviewsCount: 215,
    stockStatus: 'in_stock',
    prepTimeMinutes: 15,
    featured: true,
    variants: [
      { id: 'var-mac-12', name: 'Caja x 12 unidades', portions: 12, price: 24.0, sku: 'MAC-12', isAvailable: true },
      { id: 'var-mac-24', name: 'Caja x 24 unidades', portions: 24, price: 44.0, sku: 'MAC-24', isAvailable: true },
    ],
  },
  {
    id: 'prod-croissant-almendras',
    name: 'Croissant aux Amandes Pur Beurre',
    slug: 'croissant-aux-amandes',
    tagline: 'Hojaldre laminado artesanal con frangipane y láminas de almendra tostada.',
    description: 'Croissant de masa madre horneado dos veces, relleno con crema frangipane de almendras y terminado con azúcar glas nevada y almendras fileteadas doradas al punto justo.',
    price: 4.8,
    categoryId: 'cat-panaderia',
    images: [
      'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=800&q=80',
    ],
    ingredients: ['Harina de fuerza', 'Mantequilla francesa AOP Charentes-Poitou', 'Crema de almendras', 'Almendras fileteadas'],
    allergens: ['Gluten', 'Lácteos', 'Huevos', 'Almendras'],
    calories: 390,
    isGlutenFree: false,
    isVegan: false,
    isCustomizable: false,
    rating: 4.9,
    reviewsCount: 310,
    stockStatus: 'in_stock',
    prepTimeMinutes: 10,
    featured: false,
    variants: [
      { id: 'var-cr-1', name: 'Pieza individual', portions: 1, price: 4.8, sku: 'CR-IND', isAvailable: true },
      { id: 'var-cr-4', name: 'Pack degustación x 4', portions: 4, price: 17.5, sku: 'CR-PK4', isAvailable: true },
    ],
  },
  {
    id: 'prod-cheesecake-vasco',
    name: 'Basque Burnt Cheesecake con Vainilla',
    slug: 'basque-burnt-cheesecake',
    tagline: 'Centro ultra cremoso casi fundente y corteza caramelizada irresistible.',
    description: 'La célebre tarta de queso al estilo Donostia, horneada a muy alta temperatura para crear un exterior tostado acaramelado y un corazón sedoso con toque de vainilla Bourbon pura.',
    price: 36.0,
    categoryId: 'cat-pasteles-autor',
    images: [
      'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&w=800&q=80',
    ],
    ingredients: ['Queso crema de alta gama', 'Nata fresca 38% M.G.', 'Huevos camperos', 'Azúcar de caña', 'Vaina de vainilla'],
    allergens: ['Lácteos', 'Huevos'],
    isGlutenFree: true,
    isVegan: false,
    isCustomizable: true,
    rating: 4.9,
    reviewsCount: 180,
    stockStatus: 'in_stock',
    prepTimeMinutes: 40,
    featured: true,
    variants: [
      { id: 'var-ch-8p', name: 'Mediana (8-10 porciones)', portions: 10, price: 36.0, sku: 'CH-10P', isAvailable: true },
      { id: 'var-ch-12p', name: 'Grande (14 porciones)', portions: 14, price: 54.0, sku: 'CH-14P', isAvailable: true },
    ],
  },
  {
    id: 'prod-tarta-maracuya-vegan',
    name: 'Tarta Cacao & Maracuyá (Vegan)',
    slug: 'tarta-cacao-maracuya-vegan',
    tagline: '100% de origen vegetal: mousse de chocolate amargo y coulis brillante de maracuyá.',
    description: 'Base de frutos secos y dátiles Medjool, mousse aterciopelada de chocolate negro 72% con leche de coco emulsionada, y glaseado brillante de fruta de la pasión fresca.',
    price: 32.0,
    categoryId: 'cat-sin-gluten',
    images: [
      'https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?auto=format&fit=crop&w=800&q=80',
    ],
    ingredients: ['Dátiles Medjool', 'Nueces pecán', 'Chocolate 72% origen Ecuador', 'Leche de coco', 'Pulpa de maracuyá'],
    allergens: ['Frutos secos'],
    calories: 290,
    isGlutenFree: true,
    isVegan: true,
    isCustomizable: false,
    rating: 4.7,
    reviewsCount: 63,
    stockStatus: 'in_stock',
    prepTimeMinutes: 30,
    featured: false,
    variants: [
      { id: 'var-veg-8p', name: '8 porciones', portions: 8, price: 32.0, sku: 'VEG-08P', isAvailable: true },
    ],
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ord-1001',
    orderNumber: 'PAST-2026-0042',
    customerName: 'Lucía Fernández',
    customerEmail: 'lucia.fernandez@example.com',
    customerPhone: '+34 612 345 678',
    status: 'in_preparation',
    deliveryType: 'delivery',
    scheduledDate: '2026-09-26',
    scheduledTime: '15:00 - 17:00',
    items: [
      {
        id: 'item-1',
        productId: 'prod-opera-noir',
        productName: 'Gâteau Opéra Grand Cru',
        productImage: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80',
        variantName: '6 a 8 Porciones',
        quantity: 1,
        unitPrice: 34.0,
        totalPrice: 34.0,
        customMessage: '¡Feliz Cumpleaños Mamá!',
      },
      {
        id: 'item-2',
        productId: 'prod-macarons-prestige',
        productName: 'Coffret Prestige 12 Macarons',
        productImage: 'https://images.unsplash.com/photo-1569864321318-64445eb07464?auto=format&fit=crop&w=800&q=80',
        variantName: 'Caja x 12 unidades',
        quantity: 1,
        unitPrice: 24.0,
        totalPrice: 24.0,
      },
    ],
    subtotal: 58.0,
    tax: 5.8,
    deliveryFee: 4.5,
    discount: 0,
    total: 68.3,
    paymentStatus: 'paid',
    paymentMethod: 'card',
    createdAt: '2026-09-25T09:30:00Z',
    updatedAt: '2026-09-25T10:00:00Z',
  },
];
